<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;

/**
 * Baby Tier Curriculum — 0 to 24 months
 *
 * All activities are parent guides. Babies do not use tablets.
 * These are evidence-based, age-staged parenting guides for new mothers
 * covering sensory development, motor milestones, language acquisition,
 * cognitive growth, social bonding, daily routines, character seeds,
 * and (for Muslim households) early Quran exposure.
 *
 * Content policy:
 *   - No instrumental music. Vocal/duff/a cappella only.
 *   - No media character references.
 *   - subject='quran' gated to Muslim households at the model layer.
 *   - All descriptions begin with "For parents:"
 */
class BabyActivitySeeder extends Seeder
{
    public function run(): void
    {
        foreach (array_chunk($this->activities(), 50) as $chunk) {
            foreach ($chunk as $data) {
                Activity::updateOrCreate(
                    ['title' => $data['title']],
                    array_merge(['instructions' => $data['description'] ?? null], $data, ['language' => 'en', 'like_count' => 0])
                );
            }
        }
    }

    private function activities(): array
    {
        return [

            // ═══════════════════════════════════════════════════════
            // SENSORY (18) — visual, tactile, auditory, vestibular
            // ═══════════════════════════════════════════════════════
            ['title' => 'High-Contrast Card Gazing',           'emoji' => '⬛', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0,    'age_max' => 0.25, 'is_free' => true,  'duration' => 5,  'activity_type' => 'observation', 'skill' => 'Visual focus development',         'description' => 'For parents: Hold a bold black-and-white card 20–30 cm from baby\'s face during alert time. Newborn eyes focus best at this distance, and high-contrast patterns powerfully activate the visual cortex in the first weeks of life.'],
            ['title' => 'Soft Rattle Auditory Tracking',        'emoji' => '🎀', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.17, 'age_max' => 0.75, 'is_free' => true,  'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Auditory tracking',                'description' => 'For parents: Gently shake a soft rattle to the left, right, then above baby\'s line of sight. Encouraging the head to turn toward sound strengthens the neck and builds the auditory-motor coordination loop.'],
            ['title' => 'Texture Exploration Board',            'emoji' => '🖐️','age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'sensory',     'skill' => 'Tactile discrimination',           'description' => 'For parents: Attach fabric swatches (velvet, bubble wrap, felt, sandpaper, silk) to a cardboard board and guide baby\'s palm across each one, naming the texture. Tactile input builds neural pathways that later support fine motor control and sensory processing.'],
            ['title' => 'Mirror Gazing',                        'emoji' => '🪞', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.25, 'age_max' => 1.0,  'is_free' => true,  'duration' => 8,  'activity_type' => 'observation', 'skill' => 'Self-recognition development',     'description' => 'For parents: Hold baby in front of a baby-safe mirror and narrate what they see — "That\'s you! Look at those eyes!" Babies are fascinated by faces, and mirror play is a landmark step on the path to self-recognition, typically achieved around 18 months.'],
            ['title' => 'Nature Sounds Listening Walk',         'emoji' => '🌿', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 15, 'activity_type' => 'outdoor',     'skill' => 'Auditory environment mapping',     'description' => 'For parents: Carry baby outside and pause near birdsong, rustling leaves, or running water. Point and say "Listen — birds!" Exposure to varied natural sounds enriches the auditory cortex and builds concentration skills.'],
            ['title' => 'Soft Fabric Squares Discovery',        'emoji' => '🧶', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0,    'age_max' => 1.0,  'is_free' => true,  'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Tactile sensitivity',              'description' => 'For parents: Drape small squares of different fabrics (muslin, fleece, cotton, satin) gently over baby\'s hands and feet. Even newborns process tactile input; this safe exposure builds sensory tolerance and awareness.'],
            ['title' => 'Light and Shadow Play',                'emoji' => '💡', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.17, 'age_max' => 1.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'observation', 'skill' => 'Visual contrast sensitivity',      'description' => 'For parents: Use a small torch to cast moving shadows on the wall near baby during a dim wakeful period. Visual tracking of moving objects strengthens the oculomotor muscles and stimulates depth perception pathways.'],
            ['title' => 'Water Sensory Basin',                  'emoji' => '💧', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => true,  'duration' => 15, 'activity_type' => 'sensory',     'skill' => 'Fluid properties exploration',    'description' => 'For parents: Let baby sit and splash in a shallow basin of warm water with floating objects (cups, rubber boats). Pouring and splashing develops cause-and-effect thinking and fine motor control simultaneously.'],
            ['title' => 'Crunchy Paper Exploration',            'emoji' => '📰', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => true,  'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Bimanual coordination',            'description' => 'For parents: Let baby crinkle and scrunch a sheet of tissue or greaseproof paper (supervised; not small enough to swallow). The crinkle sound creates motivated reaching and grasping, building hand-eye coordination and grip strength.'],
            ['title' => 'Cooked Pasta Sensory Tray',            'emoji' => '🍝', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 20, 'activity_type' => 'sensory',     'skill' => 'Proprioceptive input integration', 'description' => 'For parents: Place cooled cooked spaghetti in a shallow tray and let baby squish and drag it. Messy play activates proprioceptive receptors and prepares the nervous system for writing and tool use later in childhood.'],
            ['title' => 'Ice Cube Discovery',                   'emoji' => '🧊', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'sensory',     'skill' => 'Temperature discrimination',      'description' => 'For parents: Place one or two ice cubes in a bowl and let baby touch them briefly (always supervised for safety). Temperature contrast activates a unique class of sensory receptors and introduces the concept that objects can change state.'],
            ['title' => 'Bell Shaker Exploration',              'emoji' => '🔔', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.25, 'age_max' => 1.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Cause and effect through sound',  'description' => 'For parents: Place a small wrist bell on baby\'s wrist or ankle. As baby moves, the sound follows — this teaches the fundamental concept that one\'s own actions produce effects in the world, a cornerstone of cognitive development.'],
            ['title' => 'Foil Crinkle Sheet',                   'emoji' => '✨', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.25, 'age_max' => 0.75, 'is_free' => false, 'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Visual-auditory cross-modal link', 'description' => 'For parents: Crinkle a sheet of silver foil within baby\'s line of sight. The reflective surface and crinkle sound simultaneously stimulate both visual and auditory cortices, strengthening cross-modal sensory integration.'],
            ['title' => 'Scented Cloth Discovery',              'emoji' => '🌸', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Olfactory memory formation',       'description' => 'For parents: Dab a small piece of fabric with safe natural scents — rose water, lavender, or fresh orange peel — and hold it near baby\'s nose briefly. Smell is the most direct sense tied to memory; early positive scent associations support emotional development.'],
            ['title' => 'Outdoor Grass Touch',                  'emoji' => '🌱', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 12, 'activity_type' => 'outdoor',     'skill' => 'Nature tactile tolerance',         'description' => 'For parents: Sit baby on a soft blanket with bare feet or hands touching grass. The varied textures of nature (grass, soil, leaves) provide rich tactile input that indoor environments cannot replicate, building sensory tolerance and a connection with the natural world.'],
            ['title' => 'Colour Discovery: Primary Colours',    'emoji' => '🎨', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => false, 'duration' => 10, 'activity_type' => 'observation', 'skill' => 'Colour differentiation',          'description' => 'For parents: Hold up bold red, yellow, and blue objects one at a time, pausing on each and naming the colour clearly. Colour vocabulary develops through repetitive labelling long before baby can produce the words — you are building the mental schema now.'],
            ['title' => 'Musical Crinkling Toy Exploration',    'emoji' => '🎵', 'age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 0.33, 'age_max' => 1.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'sensory',     'skill' => 'Multi-sensory integration',        'description' => 'For parents: Use a soft toy that crinkles and has varied textures. Let baby bat at it while on tummy or back. Objects that engage several senses simultaneously produce denser neural connections than single-sense stimulation.'],
            ['title' => 'Sand Play in a Tray',                  'emoji' => '🏖️','age_tier' => 'baby', 'subject' => 'sensory',   'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 20, 'activity_type' => 'sensory',     'skill' => 'Fine motor tactile play',          'description' => 'For parents: Pour clean kinetic sand or clean beach sand into a shallow tray and let baby dig, scoop, and pour. This is one of the richest sensory experiences available and directly prepares the hand muscles and coordination for future writing.'],

            // ═══════════════════════════════════════════════════════
            // MOTOR (18) — gross and fine motor milestones
            // ═══════════════════════════════════════════════════════
            ['title' => 'Tummy Time: Newborn Start',            'emoji' => '🐛', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0,    'age_max' => 0.25, 'is_free' => true,  'duration' => 5,  'activity_type' => 'hands_on',    'skill' => 'Neck extensor strength',           'description' => 'For parents: Begin with 2–3 minutes of tummy time on your chest immediately after birth. Chest-to-chest tummy time is equally beneficial as floor time in early weeks and is calming for baby. The goal is to build the neck and upper back muscles needed for head control.'],
            ['title' => 'Tummy Time: 2–4 Months Progression',  'emoji' => '🐣', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.17, 'age_max' => 0.5,  'is_free' => true,  'duration' => 8,  'activity_type' => 'hands_on',    'skill' => 'Head and chest lift',              'description' => 'For parents: By 8 weeks, aim for 20–30 cumulative minutes of daily tummy time spread across wake windows. Place a rolled towel under baby\'s chest for support if needed. By 4 months, baby should lift the head to 90° and push up on forearms.'],
            ['title' => 'Supported Sitting Practice',           'emoji' => '🧸', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.33, 'age_max' => 0.75, 'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Core and trunk stabilisation',     'description' => 'For parents: Between feeds, prop baby in a supported sit with rolled blankets or a Boppy pillow. Occasionally let baby feel the micro-corrections of balance without full support — this activates the postural muscles of the core, back, and neck.'],
            ['title' => 'Reaching for Hanging Objects',         'emoji' => '🎯', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.25, 'age_max' => 0.75, 'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Intentional reach and grasp',      'description' => 'For parents: Hang a colourful toy or fabric strip just beyond easy reach during lay-on-back play. Motivated reaching is the first voluntary motor act and builds the eye-hand coordination that underpins all future fine motor skills.'],
            ['title' => 'Rolling: Back to Tummy',               'emoji' => '🌀', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.33, 'age_max' => 0.75, 'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Rotational core strength',         'description' => 'For parents: Place a enticing toy to one side during floor play to motivate baby to roll. You can gently assist by guiding the hip and shoulder. Rolling develops the trunk rotation essential for crawling and all walking mechanics.'],
            ['title' => 'Crawling Encouragement Tunnel',        'emoji' => '🚇', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.5,  'age_max' => 1.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Cross-lateral coordination',       'description' => 'For parents: Make a low tunnel from a box or a sheet draped over chairs and place a favourite toy at the far end. Crawling on hands and knees is the single most important gross motor milestone — it integrates both brain hemispheres and directly supports reading and writing development. Do not rush babies through with walkers.'],
            ['title' => 'Pull to Stand at Furniture',           'emoji' => '🪑', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.75, 'age_max' => 1.25, 'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Lower limb strengthening',         'description' => 'For parents: Place baby near a sturdy low table or sofa edge with a toy on top. Encourage pulling to stand by reaching for the toy. The repeated pull-up action strengthens hip extensors and prepares the gait muscles for first steps. Ensure the furniture cannot tip.'],
            ['title' => 'First Steps: Cruising Practice',       'emoji' => '🚶', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.75, 'age_max' => 1.25, 'is_free' => false, 'duration' => 15, 'activity_type' => 'hands_on',    'skill' => 'Dynamic balance',                  'description' => 'For parents: Once baby pulls to stand, encourage cruising (side-stepping along furniture) by placing toys a few steps along the furniture. Barefoot on a non-slip surface is optimal — shoes are unnecessary until baby is confidently walking outdoors.'],
            ['title' => 'Ball Rolling Exchange',                'emoji' => '⚽', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'game',        'skill' => 'Bilateral coordination',           'description' => 'For parents: Sit facing baby with legs apart and roll a soft ball back and forth. This rhythmic exchange builds bilateral arm coordination, turn-taking, and the concept of reciprocal social play — all critical developmental milestones.'],
            ['title' => 'Stacking Rings: Introduction',         'emoji' => '🎪', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.75, 'age_max' => 1.5,  'is_free' => false, 'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Release and placement precision',  'description' => 'For parents: Show baby how to place rings onto a stacking post. At first, placing one ring is a major achievement. The challenge of guiding a ring hole precisely over a post develops the fine motor precision that will later be needed for writing implements.'],
            ['title' => 'Stair Climbing: Supervised Practice',  'emoji' => '🪜', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Alternating leg motor planning',   'description' => 'For parents: Allow supervised stair climbing (always beside baby). Going up and coming down (feet first on tummy initially) builds hip flexors, body awareness, and spatial reasoning. This is a Montessori-aligned practice of allowing age-appropriate physical challenge.'],
            ['title' => 'Pincer Grasp Practice: Puffs',         'emoji' => '🫙', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.75, 'age_max' => 1.25, 'is_free' => false, 'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Pincer grasp development',         'description' => 'For parents: Place a few dissolvable puffs or small soft food pieces on the high chair tray. Encourage baby to pick them up individually. The pincer grasp (thumb + index finger) emerges around 8–10 months and is the foundational fine motor skill.'],
            ['title' => 'Posting Object into Container',        'emoji' => '📦', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.75, 'age_max' => 1.5,  'is_free' => false, 'duration' => 8,  'activity_type' => 'hands_on',    'skill' => 'Voluntary object release control', 'description' => 'For parents: Place a container with a wide mouth near baby with soft balls or blocks nearby. Show baby how to drop an object in, then encourage imitation. Voluntary release — letting go on purpose — is a separate and later skill to grasping.'],
            ['title' => 'Scrunching Paper Balls',               'emoji' => '📄', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => false, 'duration' => 8,  'activity_type' => 'hands_on',    'skill' => 'Hand strength and coordination',   'description' => 'For parents: Give baby crinkly paper (newspaper or tissue) and guide the hands to scrunch it into a ball. The resistance of paper while scrunching builds intrinsic hand muscle strength needed for grip and manipulation later.'],
            ['title' => 'Finger Painting on Paper',             'emoji' => '🖌️','age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 15, 'activity_type' => 'craft',       'skill' => 'Mark-making and fine motor intent', 'description' => 'For parents: Use food-safe paint or yoghurt mixed with food colouring. Let baby drag fingers across a large sheet of paper. The intentionality of leaving a mark is a precursor to drawing and writing; celebrate every line baby makes.'],
            ['title' => 'Threading: Pasta onto a Stick',        'emoji' => '🍡', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 1.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 12, 'activity_type' => 'hands_on',    'skill' => 'Bimanual tool use and precision',  'description' => 'For parents: Thread a large piece of penne pasta onto a round wooden stick together. This simple task demands both hands work cooperatively — one to hold the stick, one to guide the pasta — building the bilateral coordination needed for dressing, fastening buttons, and writing.'],
            ['title' => 'Pouring Water: Cup to Cup',            'emoji' => '🫗', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 15, 'activity_type' => 'hands_on',    'skill' => 'Wrist control and tool handling',  'description' => 'For parents: Place a small jug of water and several cups in the bath or over a tray. Let baby pour freely. Pouring requires wrist rotation, grip control, and visual-motor coordination — it is a Montessori practical life activity with powerful developmental returns.'],
            ['title' => 'Simple Two-Piece Puzzle',              'emoji' => '🧩', 'age_tier' => 'baby', 'subject' => 'motor',     'age_min' => 1.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'game',        'skill' => 'Shape matching and fine placement', 'description' => 'For parents: Use a large wooden inset puzzle with only two pieces. Show baby how to match the piece to the hole using shape cues. This combines visual processing, spatial reasoning, and fine motor control — a rich developmental task for toddlers.'],

            // ═══════════════════════════════════════════════════════
            // LANGUAGE (18) — talking, reading, naming, first words
            // ═══════════════════════════════════════════════════════
            ['title' => 'Daily Routine Narration',              'emoji' => '🗣️','age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 15, 'activity_type' => 'vocal',       'skill' => 'Language input richness',          'description' => 'For parents: Narrate everything you do as you do it — "Now I\'m changing your nappy. Here\'s the warm cloth..." The quantity and quality of language babies hear in the first three years is the single strongest predictor of vocabulary size and school readiness. No screen can substitute.'],
            ['title' => 'Reading Aloud: First Board Books',     'emoji' => '📚', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'reading',     'skill' => 'Print awareness and vocabulary',   'description' => 'For parents: Read aloud to baby from Day 1 — even newborns benefit from hearing your voice and the patterns of language. Choose board books with bold images and few words per page. Reading daily creates neural pathways for language, attention, and literacy that no other activity replaces.'],
            ['title' => 'Naming Body Parts',                    'emoji' => '👆', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => true,  'duration' => 8,  'activity_type' => 'hands_on',    'skill' => 'Body vocabulary acquisition',      'description' => 'For parents: During nappy time or bath, gently touch each body part and name it — "eyes, nose, ears, tummy." Babies learn words for things they can see and feel most easily. Consistent daily naming builds a rich internal map of vocabulary long before baby can produce the words.'],
            ['title' => 'Animal Sound Matching Game',           'emoji' => '🐮', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => true,  'duration' => 8,  'activity_type' => 'game',        'skill' => 'Sound-symbol association',         'description' => 'For parents: Hold up a picture of an animal and make its sound expressively — "Moo! The cow says moo!" Animal sounds are typically among a baby\'s very first "words" and demonstrate the conceptual link between symbols and meaning.'],
            ['title' => 'Respond to Every Coo and Babble',      'emoji' => '💬', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0,    'age_max' => 0.5,  'is_free' => true,  'duration' => 10, 'activity_type' => 'discussion',  'skill' => 'Conversational turn-taking',       'description' => 'For parents: When baby makes a sound, pause and look at them, then respond with a similar sound or a sentence. This "serve and return" interaction is the foundation of conversational language — baby learns that communication is reciprocal before producing a single word.'],
            ['title' => 'Singing Lullabies Before Sleep',       'emoji' => '🎵', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 8,  'activity_type' => 'vocal',       'skill' => 'Phonological pattern recognition',  'description' => 'For parents: Sing simple, repetitive lullabies each night. The rhythms and rhymes of song activate phonological processing areas of the brain. Babies who are sung to regularly develop stronger phonemic awareness — the ability to distinguish and manipulate the sounds of language.'],
            ['title' => 'First Words Expansion',                'emoji' => '💡', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.75, 'age_max' => 1.5,  'is_free' => true,  'duration' => 10, 'activity_type' => 'discussion',  'skill' => 'Vocabulary expansion (expansion technique)', 'description' => 'For parents: When baby says a word (e.g., "dada"), respond by expanding it into a sentence — "Yes! Dada is sitting. Dada is reading." This expansion technique is one of the most evidence-based ways to grow vocabulary and grammatical complexity during the first-words stage.'],
            ['title' => 'Two-Word Phrase Building',             'emoji' => '🔤', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 1.25, 'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'discussion',  'skill' => 'Syntax foundation building',       'description' => 'For parents: Model two-word phrases throughout the day — "more milk," "big dog," "Mama sit." Around 18–24 months, the neurological readiness for combining words emerges; hearing lots of two-word combinations primes baby to produce them.'],
            ['title' => 'Pointing and Naming Walk Indoors',     'emoji' => '🏠', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'observation', 'skill' => 'Referential pointing comprehension', 'description' => 'For parents: Walk around your home with baby and point to objects, naming each one clearly — "table, lamp, door, plant." Pointing is a joint attention skill that underpins language; babies who are pointed at objects frequently develop vocabularies significantly faster.'],
            ['title' => 'Simple Instructions Game',             'emoji' => '🎯', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 1.0,  'age_max' => 1.75, 'is_free' => false, 'duration' => 10, 'activity_type' => 'game',        'skill' => 'Receptive language comprehension', 'description' => 'For parents: Give baby simple one-step instructions and celebrate when followed — "Bring me the ball!" Comprehension always precedes production; babies understand far more than they can say. This game builds both listening skills and the satisfaction of successful communication.'],
            ['title' => 'Bilingual Naming (Two Languages)',     'emoji' => '🌍', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'vocal',       'skill' => 'Bilingual phoneme mapping',        'description' => 'For parents: Name objects consistently in both languages — if Arabic and English are used in the home, say both. Babies raised bilingually demonstrate stronger executive function, enhanced phonemic awareness, and greater cognitive flexibility throughout life. The "confusion" period is temporary.'],
            ['title' => 'Nursery Rhyme Repetition',             'emoji' => '🎶', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'vocal',       'skill' => 'Phonological pattern memory',      'description' => 'For parents: Repeat the same 4–5 nursery rhymes daily. Predictable language patterns and repetition accelerate language absorption; babies who know many rhymes before age 3 become stronger readers. Leave pause gaps ("Jack and Jill went up the...") to invite participation.'],
            ['title' => 'Word-Object Association Cards',        'emoji' => '🃏', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'reading',     'skill' => 'Symbol-to-object matching',        'description' => 'For parents: Use flashcards or homemade cards that show one clear image (apple, car, star) with the printed word beneath. Say the word clearly, then find the real object. This bridges the gap between images and real-world referents — a key step toward literacy.'],
            ['title' => 'Favourite Book Reread',                'emoji' => '📖', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'reading',     'skill' => 'Story comprehension and prediction', 'description' => 'For parents: Read the same book ten times in a row if baby demands it — this is highly productive, not boring. Rereading deepens comprehension, enriches vocabulary retention, and builds the ability to predict and anticipate story structure.'],
            ['title' => 'Simple Question Conversations',        'emoji' => '🤔', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 1.25, 'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'discussion',  'skill' => 'Question comprehension',           'description' => 'For parents: Ask simple questions during play and wait 5–10 seconds for a response — "Where is the dog?" or "What does the cat say?" Wait patiently; the 10-second wait is critical and scientifically proven to elicit more advanced language than immediately answering for them.'],
            ['title' => 'Book Page Turning Practice',           'emoji' => '📕', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.75, 'age_max' => 1.5,  'is_free' => false, 'duration' => 8,  'activity_type' => 'reading',     'skill' => 'Print directionality and book handling', 'description' => 'For parents: Guide baby\'s hand to turn board book pages from right to left (or left to right in Arabic). The physical act of page-turning teaches print directionality, book orientation, and the concept of narrative sequence — prereading skills established before age 2.'],
            ['title' => 'Descriptive Outdoor Commentary',       'emoji' => '🌳', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 20, 'activity_type' => 'outdoor',     'skill' => 'Environmental vocabulary building', 'description' => 'For parents: On every walk, describe what you see in rich language — "A big fluffy cloud! The wind is moving the trees, look!" Outdoor commentary exposes baby to a vast vocabulary of nature, weather, and spatial words that rarely appear in indoor conversations.'],
            ['title' => 'Gesture and Sign Language Pairs',      'emoji' => '🤌', 'age_tier' => 'baby', 'subject' => 'language',  'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => false, 'duration' => 8,  'activity_type' => 'hands_on',    'skill' => 'Pre-verbal communication',         'description' => 'For parents: Teach 5–8 simple signs (more, milk, eat, sleep, all done) consistently alongside the spoken word. Baby signing does NOT delay speech; it reduces frustration during the pre-verbal stage and has been shown to boost later vocabulary because it confirms communication works.'],

            // ═══════════════════════════════════════════════════════
            // COGNITIVE (14) — object permanence, cause-effect, memory
            // ═══════════════════════════════════════════════════════
            ['title' => 'Object Permanence Box',                'emoji' => '🎁', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.5,  'age_max' => 1.0,  'is_free' => true,  'duration' => 8,  'activity_type' => 'game',        'skill' => 'Object permanence',               'description' => 'For parents: Drop a ball into a box with a hole in the lid and let baby watch it disappear, then hear the sound of it landing. Retrieving it and repeating teaches that objects continue to exist even when out of sight — a transformative cognitive milestone Piaget called "object permanence."'],
            ['title' => 'Peek-a-Boo with a Cloth',             'emoji' => '👀', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.33, 'age_max' => 1.0,  'is_free' => true,  'duration' => 8,  'activity_type' => 'game',        'skill' => 'Object permanence and anticipation', 'description' => 'For parents: Cover your face with a cloth, pause two seconds, then reveal yourself with "Peekaboo!" The delay builds anticipation — a precursor to working memory. Baby\'s excited reaction to your reappearance shows the developing understanding that you continue to exist when hidden.'],
            ['title' => 'Cause and Effect: Light Switch',       'emoji' => '💡', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.5,  'age_max' => 1.25, 'is_free' => true,  'duration' => 5,  'activity_type' => 'observation', 'skill' => 'Causal reasoning',                'description' => 'For parents: Hold baby near a light switch and let them push it. "You did that! The light went on!" Being the agent of a change in the environment is profoundly motivating and teaches the fundamental principle that actions have consequences.'],
            ['title' => 'Nesting Cups: Stack and Sort',         'emoji' => '🥛', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.75, 'age_max' => 1.5,  'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Size seriation and spatial reasoning', 'description' => 'For parents: Provide a set of nesting cups and let baby stack, knock down, and nest freely. Figuring out which cup fits inside which requires spatial reasoning and trial-and-error problem solving — two of the most critical early cognitive skills.'],
            ['title' => 'Shape Sorter: Introduction',           'emoji' => '🔷', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Shape discrimination and matching', 'description' => 'For parents: Start with a simple 3-shape sorter. Show baby the circle first (easiest to orient). This task requires visual shape discrimination, spatial reasoning, and motor control — three systems working together, which is why it\'s one of the richest toys available.'],
            ['title' => 'Imitation Games: Copy Parent',         'emoji' => '🪞', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.5,  'age_max' => 1.25, 'is_free' => false, 'duration' => 8,  'activity_type' => 'game',        'skill' => 'Deferred imitation',              'description' => 'For parents: Bang a cup on the table twice, pause, wait for baby to copy. Clap a rhythm. Wave. Initially baby imitates immediately (immediate imitation); from 9 months they begin deferred imitation — copying something minutes later, which requires memory. Both are cognitive milestones.'],
            ['title' => 'Two-Piece Simple Puzzle',              'emoji' => '🧩', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Visual-spatial matching',         'description' => 'For parents: A 2-piece wooden puzzle where each piece is a recognisable shape or animal. Guide baby to look at the shape and then try the hole. Problem-solving through trial and error, without rushing to fix it for them, builds cognitive persistence.'],
            ['title' => 'Colour Sorting: Two Bins',             'emoji' => '🔴', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Category sorting by attribute',   'description' => 'For parents: Place a red bin and a blue bin on the floor with a mix of red and blue objects. Show baby "red goes here, blue goes here." Sorting by attribute is a precursor to mathematical classification and logical thinking.'],
            ['title' => 'Searching Under a Cloth',              'emoji' => '🔍', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.5,  'age_max' => 1.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'game',        'skill' => 'Object permanence search',        'description' => 'For parents: Hide a favourite toy under a cloth in plain view and ask "Where did it go?" Allow baby to pull the cloth away and find it. Piaget charted this as Stage 4 object permanence (around 8–9 months) — a pivotal leap in cognitive development.'],
            ['title' => 'Building with Large Soft Blocks',      'emoji' => '🧱', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 12, 'activity_type' => 'hands_on',    'skill' => 'Spatial construction and planning', 'description' => 'For parents: Stack 4–6 large foam blocks with baby, naming the colours and the actions — "on top, underneath, next to." Building and knocking down structures introduces spatial vocabulary, physics concepts (balance, gravity), and the planning required for sequential construction.'],
            ['title' => 'Fill-and-Empty Container Game',        'emoji' => '🪣', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.75, 'age_max' => 1.5,  'is_free' => false, 'duration' => 10, 'activity_type' => 'hands_on',    'skill' => 'Containment concept and quantity', 'description' => 'For parents: Offer a bucket of balls or toys and let baby repeatedly empty and refill it. At this age babies are in a sensitive period for "containment schemas" — the urge to put things in and take them out. This repetitive play is cognitively rich and deeply satisfying.'],
            ['title' => 'Anticipation Shake Game',              'emoji' => '🎊', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.25, 'age_max' => 0.75, 'is_free' => false, 'duration' => 8,  'activity_type' => 'game',        'skill' => 'Anticipatory memory',             'description' => 'For parents: Begin a familiar song ("Round and Round the Garden") slowly, pausing long before the tickle at the end. Watch baby\'s body tense in anticipation — this is a beautiful window into the developing memory and prediction system that will power all future learning.'],
            ['title' => 'Matching Pairs: Simple Photo Cards',   'emoji' => '🖼️','age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 1.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'game',        'skill' => 'Visual memory and matching',      'description' => 'For parents: Print two copies of 4–6 photos (family members, familiar objects) and let baby match pairs placed face up. Simple matching games build visual discrimination, memory, and the concept of "same" — a foundational mathematical concept.'],
            ['title' => 'Drop and Retrieve Exploration',        'emoji' => '🎈', 'age_tier' => 'baby', 'subject' => 'cognitive', 'age_min' => 0.5,  'age_max' => 1.25, 'is_free' => false, 'duration' => 8,  'activity_type' => 'game',        'skill' => 'Gravity concept and object tracking', 'description' => 'For parents: Sit baby in a high chair and let them drop objects from the tray one by one. This repetitive dropping game is babies studying gravity and testing object permanence — each drop is a self-directed science experiment. Retrieve patiently and allow many repetitions.'],

            // ═══════════════════════════════════════════════════════
            // SOCIAL (14) — bonding, emotional intelligence, empathy
            // ═══════════════════════════════════════════════════════
            ['title' => 'Skin-to-Skin Contact',                 'emoji' => '🤱', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0,    'age_max' => 0.5,  'is_free' => true,  'duration' => 30, 'activity_type' => 'routine',     'skill' => 'Secure attachment formation',      'description' => 'For parents: Practice skin-to-skin as much as possible in the first weeks — baby\'s bare chest on your bare chest. This regulates baby\'s temperature, heart rate, and cortisol levels, while flooding both of you with oxytocin. It is the biological foundation of secure attachment.'],
            ['title' => 'Face-to-Face Engagement',              'emoji' => '😊', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0,    'age_max' => 0.5,  'is_free' => true,  'duration' => 10, 'activity_type' => 'observation', 'skill' => 'Social smile and mutual gaze',     'description' => 'For parents: Hold baby at face distance (20–30 cm) during a calm, alert state and make exaggerated, slow facial expressions — wide eyes, big smile, open mouth. Babies are hardwired to study faces, and this face-to-face time activates mirror neurons essential for social development.'],
            ['title' => 'Emotional Narration',                  'emoji' => '💞', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'discussion',  'skill' => 'Emotion labelling and co-regulation', 'description' => 'For parents: Name baby\'s feelings as they occur — "You\'re frustrated — the toy fell. I understand." Emotion labelling is the foundation of emotional intelligence. Neuroscience shows naming feelings helps regulate them (the "name it to tame it" principle).'],
            ['title' => 'Separation Anxiety Step-by-Step',      'emoji' => '🪟', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0.5,  'age_max' => 1.25, 'is_free' => true,  'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Object permanence and trust',      'description' => 'For parents: When leaving a room, say "I\'m going to get your nappy — I\'ll be right back!" and return within 30 seconds. Consistent, predictable short separations with verbal reassurance gradually build baby\'s trust that you WILL return — the foundation of secure attachment.'],
            ['title' => 'Waving Hello and Goodbye',             'emoji' => '👋', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0.75, 'age_max' => 1.25, 'is_free' => false, 'duration' => 5,  'activity_type' => 'vocal',       'skill' => 'Social gesture development',       'description' => 'For parents: Wave enthusiastically every time someone arrives or leaves the room, saying "Hello!" or "Bye bye!" Baby will begin waving back (first as imitation, then spontaneously) around 9–10 months. This first communicative gesture is a major social milestone.'],
            ['title' => 'Turn-Taking with Peek-a-Boo',          'emoji' => '🔄', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'game',        'skill' => 'Turn-taking and social reciprocity', 'description' => 'For parents: Play peek-a-boo and then cover baby\'s face with a cloth and wait for them to pull it off — emphasise "your turn!" Turn-taking is a prerequisite for all social interaction, conversation, and play. Babies are ready to learn it actively from around 12 months.'],
            ['title' => 'Parallel Play Playdate',               'emoji' => '👫', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 30, 'activity_type' => 'game',        'skill' => 'Observational social learning',    'description' => 'For parents: Arrange playdates where two toddlers play near each other without forced sharing. "Parallel play" (playing independently alongside another child) is the natural first social play stage before co-operative play — let it happen naturally rather than forcing interaction.'],
            ['title' => 'Emotion Recognition: Happy vs Sad',    'emoji' => '😊', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 1.25, 'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'discussion',  'skill' => 'Basic emotion recognition',        'description' => 'For parents: Show simple illustrated face cards (happy and sad) and name each one expressively — make the face yourself. Ask "Can you make a happy face?" Emotion recognition vocabulary develops in stages; naming two contrasting emotions by 18 months is developmentally on track.'],
            ['title' => 'Gentle Touch Teaching',                'emoji' => '🌸', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0.75, 'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'hands_on',    'skill' => 'Prosocial behaviour foundations',  'description' => 'For parents: Guide baby\'s hand to pet an animal or touch a sibling gently, saying "Gentle! So gentle — nice touch." Modelling gentle touch with constant verbal labelling is how children learn that others feel too. This requires hundreds of repetitions before it becomes habitual.'],
            ['title' => 'Applauding Every Achievement',         'emoji' => '👏', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0.5,  'age_max' => 1.5,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Self-efficacy and motivation',     'description' => 'For parents: Celebrate every milestone expressively — clap, cheer, make a big face. Social referencing (looking at your face to gauge if something was good) develops around 9 months. Your enthusiastic positive response teaches baby that effort leads to joy — the root of intrinsic motivation.'],
            ['title' => 'Comfort Seeking Recognition',          'emoji' => '🤗', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0,    'age_max' => 1.5,  'is_free' => false, 'duration' => 10, 'activity_type' => 'routine',     'skill' => 'Attachment security',             'description' => 'For parents: Respond consistently to baby\'s cries with calm, warm reassurance. Research is unequivocal: you cannot spoil a baby. Prompt, sensitive responses build secure attachment — and securely attached children are more independent, more resilient, and more socially competent in the long run.'],
            ['title' => 'Group Singing Circle',                 'emoji' => '🎶', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 15, 'activity_type' => 'vocal',       'skill' => 'Group participation and rhythm',   'description' => 'For parents: Gather with one or two other parent-baby pairs and sing simple action songs together. Even babies who cannot participate actively absorb the social dynamics of group activity, building comfort with group settings long before nursery school.'],
            ['title' => 'Reading Emotional Cues Practice',      'emoji' => '🔍', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0,    'age_max' => 1.5,  'is_free' => false, 'duration' => 10, 'activity_type' => 'observation', 'skill' => 'Infant cue reading',              'description' => 'For parents: Observe your baby\'s communication signals: turning head away (overstimulation/stop), arching back (discomfort), gaze avoidance (needs a break), fussing at specific times (tired). Accurate cue reading reduces baby\'s stress profoundly and builds your confidence as a parent.'],
            ['title' => 'Hugging and Affectionate Touch Time',  'emoji' => '🫂', 'age_tier' => 'baby', 'subject' => 'social',    'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'routine',     'skill' => 'Oxytocin bonding system',         'description' => 'For parents: Build affectionate touch — gentle hugs, kisses, massage — into every day as a non-negotiable. Physical affection stimulates oxytocin release in both parent and child, regulates the stress system, and directly builds the neural architecture of emotional security.'],

            // ═══════════════════════════════════════════════════════
            // ROUTINE (12) — sleep, feeding, predictability
            // ═══════════════════════════════════════════════════════
            ['title' => 'Wake Windows: Month-by-Month Guide',   'emoji' => '⏰', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0,    'age_max' => 1.0,  'is_free' => true,  'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Biological rhythm regulation',    'description' => 'For parents: A wake window is the maximum time a baby can stay awake without becoming overtired. 0–6 weeks: 45–60 min; 3 months: 75–90 min; 6 months: 2–2.5 hours. Respecting wake windows prevents cortisol build-up, reduces night waking, and improves learning during alert periods.'],
            ['title' => 'Pre-Sleep Wind-Down Routine',          'emoji' => '🌙', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 15, 'activity_type' => 'routine',     'skill' => 'Circadian rhythm entrainment',    'description' => 'For parents: Create a consistent 15-minute pre-sleep sequence: dim lights → warm bath → gentle massage → feed → lullaby → put down. When the same sequence repeats nightly, baby\'s nervous system begins to anticipate sleep at the sequence\'s start — reducing sleep resistance dramatically.'],
            ['title' => 'Morning Sun Exposure',                 'emoji' => '☀️', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 15, 'activity_type' => 'outdoor',     'skill' => 'Circadian clock setting',         'description' => 'For parents: Take baby to a bright window or outside for 10–15 minutes each morning. Natural light in the first 2 hours of waking is the primary signal that sets the circadian clock. Babies exposed to morning light consistently sleep better and settle more predictably.'],
            ['title' => 'Babywearing During Daily Tasks',       'emoji' => '🧣', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0,    'age_max' => 1.0,  'is_free' => true,  'duration' => 30, 'activity_type' => 'routine',     'skill' => 'Vestibular development and bonding', 'description' => 'For parents: Carry baby in a soft carrier or sling while completing daily tasks. Babywearing provides vestibular (balance and motion) stimulation, regulates baby\'s physiology, dramatically reduces crying, and gives parents hands-free time. Babies carried more progress through motor milestones on the same schedule.'],
            ['title' => 'Nap Time Cues and Signals',            'emoji' => '😴', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0,    'age_max' => 1.5,  'is_free' => false, 'duration' => 5,  'activity_type' => 'observation', 'skill' => 'Tired cue recognition',           'description' => 'For parents: Learn your baby\'s unique tired signals before they become overtired: yawning, rubbing eyes, glazed look, decreased activity, pulling ears. Acting on early tired cues leads to faster, easier sleep. Waiting until baby is screaming causes cortisol elevation that paradoxically prevents sleep.'],
            ['title' => 'Consistent Transition Warnings',       'emoji' => '🔔', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Executive function and flexibility', 'description' => 'For parents: From around 12 months, give a 5-minute and 1-minute warning before every transition — "Five more minutes in the bath, then we get out." Predictable warnings let the developing prefrontal cortex prepare for change, dramatically reducing tantrums at transitions.'],
            ['title' => 'Bathtime Sensory and Wind-Down',       'emoji' => '🛁', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0.25, 'age_max' => 2.0,  'is_free' => false, 'duration' => 15, 'activity_type' => 'sensory',     'skill' => 'Routine signalling and sensory regulation', 'description' => 'For parents: A warm bath at the same time each evening is one of the most powerful pre-sleep tools — the core body temperature drop after a warm bath mimics the natural drop that initiates sleep. Add pouring toys from 9 months for cognitive and motor enrichment.'],
            ['title' => 'White Noise for Sleep',                'emoji' => '🌊', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0,    'age_max' => 1.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Auditory environment and sleep',  'description' => 'For parents: Low-level white noise (fan, running water recording, white noise machine) at 60–65 dB mimics the womb environment and effectively masks startling household sounds. Research supports its use as a sleep aid in the first year; reduce and phase out after 12 months as sleep matures.'],
            ['title' => 'Indoor Play Before Outdoor Time',      'emoji' => '🏠', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 15, 'activity_type' => 'routine',     'skill' => 'Predictable daily structure',     'description' => 'For parents: Create a simple but consistent daily rhythm — wake, feed, play indoors, outdoor time, nap, repeat. Predictable daily structure reduces cortisol, promotes self-regulation, and helps baby\'s developing nervous system feel safe enough to fully engage in learning.'],
            ['title' => 'First Foods Introduction Plan',        'emoji' => '🥦', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0.5,  'age_max' => 1.0,  'is_free' => false, 'duration' => 20, 'activity_type' => 'routine',     'skill' => 'Oral motor development and nutrition', 'description' => 'For parents: Introduce first foods at 6 months (WHO guidelines) with single purées or soft finger foods (baby-led weaning). Mealtimes are not just nutrition — they are also oral motor development, sensory exploration, and cultural introduction. Eat together as a family whenever possible.'],
            ['title' => 'Evening Family Connection Time',       'emoji' => '🌆', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 20, 'activity_type' => 'routine',     'skill' => 'Family attachment and belonging',  'description' => 'For parents: Create a screen-free family time each evening — simple floor play, a story, dinner together. Consistent family connection rituals build the secure base children need to explore the world. These shared moments are also the richest context for language and social development.'],
            ['title' => 'Morning Greeting Ritual',              'emoji' => '🌅', 'age_tier' => 'baby', 'subject' => 'routine',   'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Daily structure and belonging',   'description' => 'For parents: Begin each day with the same warm greeting — walk in saying "Good morning, Alhamdulillah for a new day!" with a big smile and gentle touch. Morning rituals set an emotional tone that research shows influences a child\'s engagement and mood throughout the entire day.'],

            // ═══════════════════════════════════════════════════════
            // CHARACTER (10) — values, gratitude, manners, kindness
            // ═══════════════════════════════════════════════════════
            ['title' => 'Gratitude Words in Daily Life',        'emoji' => '🙏', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => true,  'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Gratitude habit formation',        'description' => 'For parents: Say "thank you" to your baby and to everyone around you, consistently. Model receiving and giving with gratitude — "Alhamdulillah, the food is ready; thank you kitchen!" Children absorb values they observe far earlier than parents expect. Gratitude observed is gratitude learned.'],
            ['title' => 'Modelling Patience and Calm',          'emoji' => '🌊', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 10, 'activity_type' => 'routine',     'skill' => 'Emotional regulation modelling',   'description' => 'For parents: When you feel frustrated, verbalise it calmly — "I\'m feeling a little overwhelmed right now. Let me take a breath." You are your child\'s first and most powerful emotional regulation model. Every calm response to frustration is a lesson that lasts a lifetime.'],
            ['title' => 'Saying Please and Thank You',          'emoji' => '🌸', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => true,  'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Social courtesy and manners',      'description' => 'For parents: Prompt "Can we say please?" any time baby reaches or asks for something, and celebrate with delight when they comply. Manners don\'t come naturally to toddlers — they require hundreds of gentle, positive prompts. The habit built now will require zero effort in five years.'],
            ['title' => 'Celebrating Small Wins Together',      'emoji' => '🌟', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Growth mindset foundation',        'description' => 'For parents: Cheer enthusiastically every time baby achieves something — "You did it! You stacked three blocks. You worked so hard!" Praise the effort, not just the result. This "effort praise" builds a growth mindset where children believe ability grows through practice.'],
            ['title' => 'Responding Promptly to Crying',        'emoji' => '❤️', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 0,    'age_max' => 1.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Trust and secure attachment',      'description' => 'For parents: Respond to baby\'s cries promptly and warmly. Consistent responsiveness in the first year does not create spoiled children — it creates securely attached children with lower stress hormone levels, better mental health, and higher academic achievement throughout life.'],
            ['title' => 'Sharing: Toy Exchange Practice',       'emoji' => '🎁', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'game',        'skill' => 'Prosocial sharing foundations',    'description' => 'For parents: Offer baby a toy and say "Here, for you!" then extend your hand and say "For me now, thank you!" Exchange it back and celebrate. True sharing before age 3 is neurologically premature — but modelling the exchange pattern now plants the schema that \"giving\" has social reward.'],
            ['title' => 'Gentle Redirection (No Means No)',     'emoji' => '✋', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 1.0,  'age_max' => 2.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Boundary setting and impulse control', 'description' => 'For parents: Use a calm, warm but firm "No, not for touching" followed immediately by offering an appropriate alternative. Consistent, emotionally regulated boundary-setting communicates loving authority. The goal is not fear of consequences but development of internalized self-control.'],
            ['title' => 'Empathy Narration with Toys',          'emoji' => '🧸', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 8,  'activity_type' => 'discussion',  'skill' => 'Theory of mind foundations',       'description' => 'For parents: During toy play, narrate the feelings of toy characters — "Oh no, teddy fell! He\'s crying — he\'s sad. Let\'s comfort him." This "mind-mindedness" builds theory of mind — the ability to recognize that others have feelings, thoughts, and desires different from one\'s own.'],
            ['title' => 'Kindness to Animals and Plants',       'emoji' => '🌿', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 1.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'outdoor',     'skill' => 'Environmental empathy',            'description' => 'For parents: Guide baby to gently water a plant and say "We\'re giving the plant a drink — it needs water to grow, just like you." Teach gentle touch toward animals. Care for living things develops empathy, responsibility, and a sense of stewardship that mirrors Islamic teachings about being khalifah on Earth.'],
            ['title' => 'Positive Self-Image Building',         'emoji' => '💪', 'age_tier' => 'baby', 'subject' => 'character', 'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Healthy self-concept formation',   'description' => 'For parents: Tell your baby daily — using their name — that they are loved, capable, and precious. "You are so loved, [name]. Allah made you and you are wonderful." Positive, specific affirmations build the self-concept that becomes the foundation of resilience and emotional health.'],

            // ═══════════════════════════════════════════════════════
            // QURAN (14) — Muslim households only (gated at model level)
            // Listening to recitation, duas, early Islamic environment
            // ═══════════════════════════════════════════════════════
            ['title' => 'Quran as Lullaby: Surah Al-Baqarah',  'emoji' => '☪️', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 20, 'activity_type' => 'vocal',       'skill' => 'Quran phoneme exposure',           'description' => 'For parents: Play or recite Surah Al-Baqarah softly during baby\'s sleep time. The Prophet ﷺ said that Surah Al-Baqarah protects the home from Shaytan. Exposure to Quranic Arabic from birth imprints the rhythm and phonemes of the Quran into the auditory memory — the foundation of future Quran fluency.'],
            ['title' => 'Ayat Al-Kursi Before Sleep',           'emoji' => '🌙', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 5,  'activity_type' => 'vocal',       'skill' => 'Prophetic sunnah protection',      'description' => 'For parents: Recite Ayat Al-Kursi (2:255) over your sleeping baby each night, gently blowing on their face. This follows the sunnah of the Prophet ﷺ who taught that this verse provides special protection. It also creates a deeply calming bedtime ritual tied to Islamic identity from birth.'],
            ['title' => 'Bismillah Before Every Feed',          'emoji' => '🍼', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 2,  'activity_type' => 'routine',     'skill' => 'Dhikr habit formation',            'description' => 'For parents: Say "Bismillah" clearly before every breastfeed, bottle, or food introduction. The habit of beginning every action with the name of Allah is a prophetic sunnah that should be established from the very first days of life. Baby learns to associate feeding with this blessed word.'],
            ['title' => 'Al-Fatiha Morning Recitation',         'emoji' => '🌅', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 5,  'activity_type' => 'vocal',       'skill' => 'Surah memorisation exposure',      'description' => 'For parents: Recite Surah Al-Fatiha slowly and clearly to baby every morning while making eye contact. Al-Fatiha is the opening chapter of the Quran, repeated in every prayer — early daily exposure means baby will be hearing the surah thousands of times before they are old enough to consciously memorise it.'],
            ['title' => 'Surah Al-Ikhlas as Daily Dhikr',       'emoji' => '✨', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 3,  'activity_type' => 'vocal',       'skill' => 'Tawheed concept exposure',         'description' => 'For parents: Recite Surah Al-Ikhlas (just 4 verses) three times daily to baby. The Prophet ﷺ described it as equivalent in reward to a third of the Quran. Its short, rhythmic verses are among the easiest for children to memorise and introduce the foundational concept of Allah\'s oneness.'],
            ['title' => 'Surah Al-Falaq Evening Protection',    'emoji' => '🛡️','age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 3,  'activity_type' => 'vocal',       'skill' => 'Prophetic protective adhkar',      'description' => 'For parents: Recite Surah Al-Falaq and Surah An-Nas each evening, then gently blow over baby. Abu Dawud and others narrate the Prophet ﷺ recited these before sleep. Establishing these as the nightly protective routine creates a lifelong Islamic bedtime habit.'],
            ['title' => 'Surah An-Nas Morning Protection',      'emoji' => '🌤️','age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => true,  'duration' => 3,  'activity_type' => 'vocal',       'skill' => 'Morning adhkar foundation',        'description' => 'For parents: Recite Surah An-Nas three times each morning, blowing over baby afterward. Consistency in morning and evening adhkar builds an Islamic temporal rhythm into baby\'s earliest days — spiritually grounding the household routine.'],
            ['title' => 'Family Dhikr Circle: Baby Present',    'emoji' => '🤲', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0.5,  'age_max' => 2.0,  'is_free' => false, 'duration' => 10, 'activity_type' => 'routine',     'skill' => 'Islamic family culture',           'description' => 'For parents: Include baby in family dhikr circles — gather as a family after Fajr or Asr and recite Subhanallah, Alhamdulillah, Allahu Akbar. Babies absorb the emotional and spiritual atmosphere of their household. Including them normalises dhikr as a natural family activity from the beginning.'],
            ['title' => 'Azan at Birth and Milestones',         'emoji' => '🕌', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 0.5,  'is_free' => false, 'duration' => 5,  'activity_type' => 'routine',     'skill' => 'Islamic rites of passage',         'description' => 'For parents: Recite the Azan softly in baby\'s right ear at birth (as per sunnah) and also at major milestones (first tooth, first steps). The first sound Allah\'s name and the call to prayer is a prophetic tradition that establishes Islamic identity from the very first moments of earthly life.'],
            ['title' => 'Dua When Baby Cries: Al-Mu\'awwidhatain', 'emoji' => '📿','age_tier' => 'baby', 'subject' => 'quran',    'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 3,  'activity_type' => 'vocal',       'skill' => 'Dua as comfort tool',             'description' => 'For parents: When baby cries and you feel helpless, recite softly "Bismillahi arqeeka, min kulli shay\'in yu\'dheeka" (I ruqyah you in the name of Allah from everything that harms you) followed by Al-Mu\'awwidhatain. This is a sunnah ruqyah for babies and reminds parents to turn to Allah first.'],
            ['title' => 'Soft Quran Background During Play',    'emoji' => '🎵', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 30, 'activity_type' => 'observation', 'skill' => 'Passive Quran phoneme absorption', 'description' => 'For parents: Play soft, clear Quran recitation in the background during daytime play — not as entertainment but as environmental immersion. Choose clear, melodious recitations at conversational volume. Early phoneme exposure creates an "auditory template" that facilitates Quran recitation later.'],
            ['title' => 'Dua Before Sleep: Parent\'s Version',  'emoji' => '😴', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 5,  'activity_type' => 'vocal',       'skill' => 'Sleep dua habit',                  'description' => 'For parents: After placing baby down, recite: "Allahumma bismika amutu wa ahya" (O Allah, in Your name I die and I live). Model it out loud so baby hears it. By toddlerhood they will begin to say it after you — habits established in the first two years are the most enduring of a lifetime.'],
            ['title' => 'Islamic Nasheed Lullabies',            'emoji' => '🌙', 'age_tier' => 'baby', 'subject' => 'quran',     'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 15, 'activity_type' => 'vocal',       'skill' => 'Islamic identity and calm',        'description' => 'For parents: Use vocal, a cappella nasheeds (no instruments) as calming music. There are beautiful Arabic nasheeds about the Prophet ﷺ and praise of Allah composed specifically for children. These provide the emotional warmth of music within Islamic guidelines, associating Islamic content with comfort and love.'],
            ['title' => 'Hasbunallahu wa Ni\'mal Wakeel: Daily Dua', 'emoji' => '🤲','age_tier' => 'baby', 'subject' => 'quran', 'age_min' => 0,    'age_max' => 2.0,  'is_free' => false, 'duration' => 3,  'activity_type' => 'vocal',       'skill' => 'Tawakkul concept introduction',    'description' => 'For parents: Recite "Hasbunallahu wa ni\'mal wakeel" (Allah is sufficient for us, and He is the best Disposer of affairs) regularly — when baby is unwell, at difficult moments, as a reassurance. Baby absorbs the emotional calm that accompanies this dua and the concept that trust is placed in Allah above all else.'],

        ]; // end activities()
    }
}
