<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\Course;
use App\Models\Module;
use Illuminate\Database\Seeder;

/**
 * Generates ~2,200 activities (≈20 per module × 12 modules × 11 courses)
 * and links them to their parent modules via the activity_module pivot.
 */
class CurriculumSeeder extends Seeder
{
    /** Template bank: subject → array of activity title templates */
    private array $templates = [
        'Sensory & Touch' => [
            'Texture Touch Board', 'Soft vs Rough Sorting', 'Water Play Discovery',
            'Sand Sensory Bin', 'Fabric Feel Game', 'Cold & Warm Touch', 'Squishy Ball Fun',
            'Rice Pouring Play', 'Finger Paint Smush', 'Gooey Slime Explore',
            'Nature Texture Walk', 'Bubble Pop Party', 'Shaving Cream Draw',
            'Cotton Ball Cloud', 'Cornstarch Goo Lab', 'Velvet & Silk Sort',
            'Ice Cube Melt Race', 'Feather Tickle Game', 'Dough Roll & Poke', 'Jelly Squish Fun',
        ],
        'Visual Tracking' => [
            'Follow the Light', 'Black-White Card Show', 'Colourful Mobile Watch',
            'Bubble Tracking', 'Rolling Ball Follow', 'Mirror Face Game', 'Shadow Chase',
            'Flashlight Dance', 'Dangling Toy Reach', 'Peek-a-Boo Patterns',
            'Slow Moving Object', 'Contrast Card Flip', 'Spinning Wheel Watch',
            'Ribbon Trail Track', 'Puppet Follow Along', 'Toy Train Visual Chase',
            'Wind Chime Watch', 'Floating Feather Track', 'Light-Up Toy Stare', 'Laser Dot Chase',
        ],
        'Sound & Music' => [
            'Rattle Shake Time', 'Lullaby Sing-Along', 'Drum Beat Copy',
            'Clap Pattern Game', 'Nature Sounds Listen', 'Musical Instruments Intro',
            'Rhythm Sticks Tap', 'Singing Vowels', 'Animal Sound Match',
            'Whisper & Shout', 'Bell Jingle Play', 'Water Xylophone',
            'Humming Along', 'Beat the Pot Drum', 'Sound Jar Guess',
            'Stomp & Clap Rhythm', 'Rainstick Shake', 'Shaker Egg Dance',
            'Voice Echo Game', 'Wind Sound Maker',
        ],
        'Tummy Time & Movement' => [
            'Tummy Time Mirror', 'Reaching for Toys', 'Rolling Practice',
            'Crawl Tunnel Fun', 'Push-Up Wiggle', 'Kicking Ball Play',
            'Baby Yoga Stretch', 'Bouncing on Lap', 'Supported Sitting',
            'Leg Bicycle Pedal', 'Arm Lift Reach', 'Belly Surf on Blanket',
            'Head Lift Challenge', 'Sway Side-to-Side', 'Pull-to-Stand Practice',
            'Spin & Roll Ball', 'Baby Plank Game', 'Foot Stomp Dance',
            'Crawl Obstacle Course', 'Balance Ball Ride',
        ],
        'Bonding & Parent Connection' => [
            'Skin-to-Skin Cuddle', 'Story Time Together', 'Parent-Baby Dance',
            'Eye Contact Game', 'Massage & Relaxation', 'Feeding Bonding Moment',
            'Mirror Mimicry', 'Gentle Rocking', 'Hand Holding Walk',
            'Blanket Fort Hideout', 'Tickle & Giggle', 'Photo Album Talk',
            'Singing to Baby', 'Heartbeat Listening', 'Gentle Face Touch',
            'Bath Play Together', 'Outdoor Walk & Talk', 'Puzzle Solve Duo',
            'Cooking Together Simple', 'Shared Book Flip',
        ],
        'Motor Skills & Grasp' => [
            'Pincer Grasp Practice', 'Stacking Rings', 'Block Tower Build',
            'Bead Threading', 'Playdough Squeeze', 'Spoon Transfer',
            'Button Push Toy', 'Peg Board Fit', 'Zip & Unzip',
            'Shape Sorter', 'Lid Twist Open', 'Coin Drop',
            'Clothespin Clip', 'Tearing Paper', 'Cutting Practice',
            'Dot Sticker Place', 'Lacing Cards', 'Tweezers Pick',
            'Puzzle Piece Fit', 'Double-Hand Clap',
        ],
        'Royal Etiquette & Personality' => [
            'Greetings & Salaam', 'Table Manners Game', 'Please & Thank You Song',
            'Sharing Circle', 'Kindness Jar Fill', 'Polite Words Match',
            'Posture Practice', 'Napkin Folding Art', 'Guest Welcome Role-Play',
            'Compliment Chain', 'Patience Timer', 'Turn-Taking Board Game',
            'Respectful Listening', 'Clean-Up Challenge', 'Gentle Hands Song',
            'Thank You Card Craft', 'Apology Practice', 'Helping Others Story',
            'Good Manners Bingo', 'Elegant Walk Practice',
        ],
        'Quran & Islamic Studies' => [
            'Surah Al-Fatiha Listen', 'Allahu Akbar Repeat', 'Wudu Steps Song',
            'Salah Position Practice', 'Bismillah Colouring', 'Masjid Model Build',
            'Prophet Stories Listen', '99 Names Flashcard', 'Dua Before Eating',
            'Ramadan Calendar Craft', 'Eid Card Making', 'Hajj Journey Map',
            'Arabic Letter Sound', 'Islamic Pattern Art', 'Charity Box Decorate',
            'Quran Bookmark Craft', 'Moon Phases Observe', 'Kindness in Islam Story',
            'Friday Prayer Talk', 'Gratitude Journal Start',
        ],
        'Arabic Introduction' => [
            'Alif-Ba-Ta Song', 'Arabic Letter Tracing', 'Number Words in Arabic',
            'Colour Names Arabic', 'Animal Names Arabic', 'Family Words Arabic',
            'Greeting in Arabic', 'Body Parts Arabic', 'Food Words Arabic',
            'Shape Names Arabic', 'Days of Week Arabic', 'Arabic Alphabet Puzzle',
            'Arabic Writing Sand Tray', 'Arabic Story Listen', 'Arabic Number Match',
            'Arabic Letter Stamp', 'Arabic Vocab Flashcard', 'Arabic Rhyme Time',
            'Arabic Sing-Along', 'Arabic Word Bingo',
        ],
        'Arabic Language' => [
            'Arabic Sentence Build', 'Arabic Reading Practice', 'Arabic Dictation',
            'Arabic Conversation Role-Play', 'Arabic Poem Recite', 'Arabic Story Write',
            'Arabic Grammar Intro', 'Arabic Comprehension Quiz', 'Arabic Debate Starter',
            'Arabic Letter Connection', 'Arabic Vocabulary Builder', 'Arabic Listening Comp',
            'Arabic Creative Writing', 'Arabic News Summary', 'Arabic Book Review',
            'Arabic Presentation', 'Arabic Research Project', 'Arabic Interview Practice',
            'Arabic Film Discussion', 'Arabic Culture Report',
        ],
        'World Cultures & Stories' => [
            'World Map Colour', 'Cultural Flag Craft', 'Folk Tale Read-Aloud',
            'Traditional Dance Video', 'World Food Taste Test', 'Festival Calendar',
            'Cultural Dress-Up Day', 'Origami Japan', 'Rangoli India Art',
            'African Drum Circle', 'Chinese Lantern Craft', 'Bonjour France Song',
            'Turkish Mosaic Art', 'Brazilian Carnival Mask', 'Russian Matryoshka Paint',
            'Korean Hanbok Colour', 'Mexican Paper Flowers', 'Australian Dot Art',
            'Egyptian Pyramid Model', 'World Hello Day Card',
        ],
        'Life Skills & Routines' => [
            'Morning Routine Chart', 'Shoe Tying Practice', 'Teeth Brushing Song',
            'Bed Making Game', 'Laundry Sort by Colour', 'Setting the Table',
            'Grocery List Draw', 'Clock Reading Basics', 'Money Coin Sorting',
            'Phone Number Memorise', 'Address Know-How', 'Kitchen Safety Rules',
            'Packing a Bag', 'Crossing the Road', 'Weather Dressing',
            'Meal Planning Simple', 'Watering Plants', 'Pet Care Basics',
            'Tidying Up Race', 'First Aid Know-How',
        ],
        'Life Skills & Independence' => [
            'Time Management Exercise', 'Budget Building', 'Meal Prep Basics',
            'Travel Planning Activity', 'Emergency Contacts', 'Public Transport Guide',
            'Correspondence Writing', 'Interview Preparation', 'Decision-Making Game',
            'Conflict Resolution Role-Play', 'Community Service Plan', 'Recycling Sort',
            'Digital Citizenship', 'Library Research Trip', 'Self-Assessment Journal',
            'Goal Setting Workshop', 'First Aid Advanced', 'Cooking a Simple Meal',
            'Responsibility Chart', 'Independence Challenge',
        ],
        'Creative Expression' => [
            'Finger Painting Free', 'Story Illustration', 'Collage from Magazines',
            'Clay Sculpture Mini', 'Dance Freestyle', 'Puppet Show Create',
            'Song Writing Simple', 'Nature Art Collection', 'Dress-Up Drama',
            'Shadow Puppet Play', 'Watercolour Splash', 'Paper Plate Mask',
            'Cardboard Box Castle', 'Tissue Paper Flowers', 'Marble Paint Roll',
            'Leaf Print Art', 'Bottle Cap Mosaic', 'Yarn Weaving Board',
            'Recycled Art Robot', 'Musical Instrument Build',
        ],
        'First Words & Communication' => [
            'Animal Sound Imitation', 'Point & Name Objects', 'Body Part Song',
            'Simple Sign Language', 'Yes/No Game', 'Where Is It Hide',
            'Picture Card Match', 'First Books Flip', 'Babble Back Talk',
            'Name That Fruit', 'What Colour Game', 'Feed the Doll Talk',
            'Phone Role-Play', 'Song Word Fill-In', 'Story Repeat Simple',
            'Touch & Say Texture', 'Garden Walk & Talk', 'Face Expression Name',
            'Voice Tone Match', 'Action Word Demo',
        ],
        'Walking & Balance' => [
            'Walk the Line', 'Stepping Stones', 'Balance Beam Low',
            'Stair Climb Practice', 'Dancing with Scarves', 'Balloon Kick Walk',
            'Wagon Pull Walk', 'Slope Walk Up', 'Sideways Shuffle',
            'March Like a Soldier', 'Tip-Toe Sneak', 'Jump Over Rope',
            'Ball Roll & Chase', 'Freeze Dance Walk', 'Animal Walk Imitate',
            'Obstacle Course Walk', 'Pillow Path Walk', 'Sand Walk Feel',
            'Puddle Jump Fun', 'Walk & Carry Object',
        ],
        'Cause & Effect Play' => [
            'Push Button Toy', 'Jack-in-the-Box Pop', 'Ball Down Ramp',
            'Light Switch On/Off', 'Drop & Bounce Ball', 'Pull String Toy',
            'Knock Block Tower', 'Wind-Up Toy March', 'Water Pour & Fill',
            'Drum Hit Sound', 'Blow Pinwheel Spin', 'Slide Object Down',
            'Shake Rattle Noise', 'Blow Bubbles Pop', 'Pull Wagon Move',
            'Ring Doorbell Sound', 'Open Lift Flap Book', 'Splash Water Play',
            'Push Car Go', 'Stamp & See Print',
        ],
        'Sorting & Shapes' => [
            'Colour Sorting Cups', 'Shape Puzzle Fit', 'Big vs Small Sort',
            'Round Object Hunt', 'Matching Pairs Game', 'Group by Colour',
            'Shape Stamp Art', 'Shape Walk Find', 'Triangle Square Circle',
            'Nesting Cup Stack', 'Sort Buttons by Size', 'Shape Bingo',
            'Build with Shapes', 'Cookie Cutter Shapes', 'Shape Tracing',
            'Pattern Block Copy', 'Shape Scavenger Hunt', 'Felt Shape Board',
            'Shape Collage Art', 'Shape Snack Match',
        ],
        'Imitation & Social Play' => [
            'Copy My Clap', 'Pretend Cooking', 'Doll Care Role-Play',
            'Phone Conversation', 'Doctor Check-Up', 'Store Shopping Play',
            'Mirror Movement', 'Animal Pretend Play', 'Tea Party Setup',
            'Firefighter Role-Play', 'Teacher Pretend', 'Building Helper',
            'Baby Bath Time Play', 'Post Office Play', 'Farm Animal Play',
            'Pirate Adventure Play', 'Space Explorer Play', 'Chef Hat Cook',
            'Dress-Up Share Time', 'Friend Greeting Game',
        ],
        'Sensory Exploration' => [
            'Sensory Bottle Shake', 'Messy Play Tray', 'Scented Playdough',
            'Sound Shaker Match', 'Taste Test Safe', 'Light Table Play',
            'Rainbow Rice Bin', 'Water Bead Explore', 'Musical Jar Band',
            'Sandpaper Letter Touch', 'Freezer Bag Paint', 'Grass Walk Barefoot',
            'Cloud Dough Feel', 'Spaghetti Sensory Bin', 'Essential Oil Sniff',
            'Coloured Ice Explore', 'Mud Kitchen Play', 'Foil Crinkle Sound',
            'Pop-It Fidget Focus', 'Textured Ball Roll',
        ],
        'Emotions & Self-Regulation' => [
            'Feelings Face Cards', 'Calm Down Jar', 'Deep Breathing Dragon',
            'Happy/Sad Sort', 'Emotion Charades', 'Worry Monster Feed',
            'Anger Volcano Craft', 'Gratitude Flower', 'Kindness Rock Paint',
            'Feelings Thermometer', 'Yoga for Calm', 'Music Mood Match',
            'What Would You Do Cards', 'Mirror Emotion Copy', 'Peace Corner Visit',
            'Stress Ball Squeeze', 'Emotion Story Read', 'Colour Your Feeling',
            'Heart Breathing', 'Self-Portrait Emotion',
        ],
        'Counting 1–5' => [
            'Count the Bears', 'Number Finger Play', 'One-to-One Dot Match',
            'Count & Clip Cards', 'Block Tower Count', 'Sticker Count Page',
            'Apple Tree Count', 'Five Little Ducks Song', 'Count Steps Walk',
            'Numeral Tracing 1-5', 'Count Snack Time', 'Dice Roll & Count',
            'Count & Move Game', 'Magnetic Number Fish', 'Count Objects in Bag',
            'Number Puzzle 1-5', 'Count Claps Game', 'How Many Fingers',
            'Counting Book Read', 'Number Train Build',
        ],
        'Imaginative Play' => [
            'Castle Build Pretend', 'Spaceship Cardboard', 'Fairy Garden Create',
            'Superhero Cape Play', 'Monster Under Bed Story', 'Magic Wand Craft',
            'Invisible Friend Chat', 'Pirate Treasure Hunt', 'Rainbow Land Journey',
            'Under-the-Sea Play', 'Jungle Explorer', 'Cloud Shape Story',
            'Time Travel Game', 'Robot Helper Play', 'Wizard Potion Mix',
            'Dragon Egg Hatch', 'Secret Agent Mission', 'Ocean Voyage Play',
            'Dinosaur Land Play', 'Flying Carpet Ride',
        ],
        'Arts & Crafts Basics' => [
            'Finger Paint Splatter', 'Paper Tearing Collage', 'Glue & Glitter Art',
            'Sponge Stamp Print', 'Pipe Cleaner Shapes', 'Cotton Ball Glue',
            'Straw Paint Blow', 'Handprint Art', 'Paper Weaving',
            'Nature Collage', 'Pasta Necklace', 'Crayon Resist Art',
            'Popsicle Stick Build', 'Egg Carton Craft', 'Tissue Paper Sun',
            'Foam Shape Stamp', 'Paper Bag Puppet', 'Marble Roll Paint',
            'String Art Simple', 'Hole Punch Art',
        ],
        'Nature Exploration' => [
            'Leaf Collecting Walk', 'Bug Magnifier Look', 'Cloud Watching',
            'Plant a Seed', 'Rock Collection Sort', 'Bird Watching Count',
            'Rain Puddle Splash', 'Flower Petal Press', 'Ant Hill Observe',
            'Soil Dig Explore', 'Tree Bark Rubbing', 'Butterfly Life Cycle',
            'Garden Watering', 'Nature Sound Listen', 'Shell Hunt Beach',
            'Pinecone Craft', 'Worm Habitat Build', 'Weather Chart Track',
            'Outdoor Scavenger Hunt', 'Nature Journal Draw',
        ],
        'Motor Skills & Balance' => [
            'Balance Beam Walk', 'Hop on One Foot', 'Ball Catch & Throw',
            'Scissors Practice', 'Lacing Shoes Game', 'Jumping Jacks',
            'Climbing Frame Play', 'Bike Balance Ride', 'Dance Freeze Balance',
            'Yoga Tree Pose', 'Ball Bounce Count', 'Rope Skipping Intro',
            'Zigzag Run Course', 'Balance on Pillow', 'Throwing at Target',
            'Relay Race Simple', 'Hula Hoop Try', 'Stepping Stone Hop',
            'Bear Crawl Race', 'Wheelbarrow Walk Pair',
        ],
        'Alphabet & Phonics' => [
            'Letter A Sound Hunt', 'Alphabet Song Sing', 'Letter Tracing Sand',
            'Phonics Flashcard Flip', 'Initial Sound Match', 'Letter Stamp Art',
            'Alphabet Sensory Bin', 'Letter Body Shape', 'CVC Word Build',
            'Rhyming Words Basket', 'Letter of the Week', 'Sound Blending Game',
            'Magnetic Letter Sort', 'Letter Dot Paint', 'Alphabet Puzzle',
            'Phonics Bingo', 'Letter Writing Practice', 'Word Family Sort',
            'Beginning Sound Clip', 'Alphabet Book Create',
        ],
        'Numbers 1–10' => [
            'Number Line Walk', 'Count & Write 1-10', 'Number Matching Cards',
            'Ten Frame Fill', 'Counting Bears Mat', 'Number Bond Intro',
            'Math Story Problems', 'Domino Count', 'Number Order Sequence',
            'Skip Counting by 2s', 'More/Less Compare', 'Number Hunt Outdoors',
            'Dice Addition Simple', 'Number Colouring Page', 'Tally Mark Count',
            'Number Jigsaw Puzzle', 'Count Backwards Song', 'Number Snap Card Game',
            'Measurement Compare', 'Pattern Extend 1-10',
        ],
        'Storytelling & Listening' => [
            'Story Dice Roll Tell', 'Listen & Draw', 'Sequence Cards Order',
            'Puppet Story Create', 'Audio Story Listen', 'Story Retell',
            'Character Description', 'Setting Illustration', 'Plot Question Cards',
            'Memory Story Game', 'Story Starter Cards', 'Wordless Book Tell',
            'Favourite Story Share', 'Story Map Draw', 'Listen & Act Out',
            'Group Story Build', 'Story Ending Change', 'Fairy Tale Compare',
            'Story Feeling Find', 'Author Chair Share',
        ],
        'Sharing & Social Skills' => [
            'Turn-Taking Timer', 'Sharing Toy Practice', 'Friend Interview',
            'Cooperative Puzzle', 'Group Art Project', 'Emotion Check-In Circle',
            'Conflict Resolution Cards', 'Kindness Counter', 'Partner Read Aloud',
            'Team Building Block', 'Compliment Jar', 'Classroom Jobs Chart',
            'Listening Body Practice', 'Fair Play Game', 'Apology Role-Play',
            'Inclusion Activity', 'Empathy Story Read', 'Community Helper Learn',
            'Playground Rules Game', 'Friendship Bracelet',
        ],
        'Colours & Patterns' => [
            'Colour Mixing Paint', 'Pattern Bead String', 'Colour Scavenger Hunt',
            'Rainbow Order Sort', 'Colour Wheel Spin', 'AB Pattern Create',
            'Warm/Cool Colour Sort', 'Pattern Block Design', 'Colour Match Memory',
            'Shape Pattern Extend', 'Colour by Number', 'Growing Pattern Find',
            'Symmetry Fold Art', 'Colour Spectrum Explore', 'ABAB Clap Pattern',
            'Nature Colour Match', 'Tile Pattern Copy', 'Colour Story Read',
            'Pattern Walk Find', 'Colour Emotion Art',
        ],
        'STEM Basics' => [
            'Sink or Float Test', 'Magnet Explore', 'Shadow Length Measure',
            'Build a Bridge', 'Paper Airplane Test', 'Simple Circuit Light',
            'Volcano Baking Soda', 'Balance Scale Compare', 'Plant Growth Journal',
            'Water Cycle Bag', 'Gear & Wheel Play', 'Static Electricity',
            'Weather Observation', 'Bug Habitat Build', 'Gravity Drop Test',
            'Sound Vibration See', 'Colour Mixing Lab', 'Ice Melting Race',
            'Pulley Simple Machine', 'Density Column Build',
        ],
        'Drawing & Painting' => [
            'Self Portrait Draw', 'Watercolour Landscape', 'Still Life Sketch',
            'Symmetry Drawing', 'Splatter Paint Action', 'Gradient Colour Mix',
            'Pencil Shading Intro', 'Oil Pastel Blend', 'Step-by-Step Animal',
            'Abstract Art Free', 'Dot Art Mandala', 'Charcoal Drawing',
            'Perspective Simple', 'Comic Strip Create', 'Nature Sketch Outdoors',
            'Texture Drawing', 'Emotion Art Express', 'Stamp & Print Pattern',
            'Chalk Art Sidewalk', 'Scratch Art Reveal',
        ],
        'Early Writing' => [
            'Letter Formation Sheet', 'Name Writing Practice', 'Sentence Starter Prompt',
            'Journal Entry Simple', 'Label the Picture', 'Word Wall Write',
            'Story Sentence Write', 'List Writing Grocery', 'Postcard to Friend',
            'Copy a Poem', 'Dictation Simple', 'Fill in the Blank',
            'Descriptive Sentence', 'Opinion Sentence Write', 'Thank You Note',
            'Caption for Drawing', 'Sight Word Write', 'What I Like List',
            'Story Ending Write', 'Letter to Grandparent',
        ],
        'Rhymes & Poetry' => [
            'Nursery Rhyme Sing', 'Rhyming Word Game', 'Poem Read-Aloud',
            'Rhyme Time Match', 'Clap the Syllables', 'Acrostic Poem',
            'Limerick Intro', 'Rhyming Couplet Write', 'Rhythm & Beat',
            'Poem Illustration', 'Haiku Simple', 'Tongue Twister Challenge',
            'Rhyme Fill-In Song', 'Poetry Recitation', 'Silly Rhyme Create',
            'Word Family Rhyme', 'Rhyming Scavenger Hunt', 'Poem Memory Recite',
            'Rhyme & Move Dance', 'Favourite Poem Share',
        ],
        'Counting 11–20' => [
            'Teen Number Tracing', 'Count to 20 Song', 'Ten-and-More Concept',
            'Number Line 11-20', 'Place Value Blocks', 'Twenty Frame Fill',
            'Counting by 2s to 20', 'Number Order 11-20', 'Teen Number Match',
            'Skip Count by 5s', 'Addition to 20', 'Subtraction from 20',
            'Number Word Match', 'Estimation Jar', 'Measurement with Objects',
            'Graphing 11-20', 'Money Counting Intro', 'Time to Hour',
            'Story Problem 11-20', 'Pattern Continue 11-20',
        ],
        'Simple Science' => [
            'States of Matter', 'Magnet Strength Test', 'Plant Parts Label',
            'Animal Habitat Match', 'Weather Wheel Spin', 'Five Senses Explore',
            'Colour Changing Celery', 'Ramp Speed Test', 'Dissolve or Not',
            'Shadow Puppet Science', 'Sound Travel In Water', 'Seed Germination Watch',
            'Static Electricity Hair', 'Smell Test Blindfold', 'Insect Body Parts',
            'Float or Sink Predict', 'Light & Dark Room', 'Rock Type Sort',
            'Thermometer Read', 'Magnetic vs Non-Magnetic',
        ],
        'Social-Emotional Learning' => [
            'Emotion Flashcards', 'How Are You Today Circle', 'Empathy Story Read',
            'Gratitude Journal', 'Conflict Resolution Play', 'Self-Esteem Affirmation',
            'Growth Mindset Story', 'Worry Box Write', 'Meditation Minute',
            'Random Act of Kindness', 'Feelings Charades', 'Calm Corner Visit',
            'Boundary Setting Practice', 'Goal Setting Card', 'Self-Care Activity',
            'Perspective Taking Game', 'Stress Ball Make', 'Positive Self-Talk Mirror',
            'Cooperation Challenge', 'Community Service Plan',
        ],
        'Reading Readiness' => [
            'Sight Word Flashcards', 'Sound Out CVC Words', 'Reading Fluency Practice',
            'Comprehension Question Cards', 'Book Walk Preview', 'Guided Reading Group',
            'Independent Reading Log', 'Word Family Cards', 'Vocabulary Builder',
            'Reading Response Journal', 'Non-Fiction vs Fiction Sort', 'Main Idea Find',
            'Character Trait Chart', 'Story Element Map', 'Prediction Before Reading',
            'Author Study', 'Text Features Hunt', 'Reading Buddy Session',
            'Word Attack Strategy', 'Library Visit Explore',
        ],
        'World Cultures' => [
            'World Map Colouring', 'Cultural Food Tasting', 'Traditional Music Listen',
            'Country Flag Match', 'World Hello Greeting', 'Folk Story Read',
            'Cultural Dance Learn', 'Craft from Country', 'Currency Compare',
            'World Landmark Model', 'Language Phrase Book', 'Holiday Tradition Learn',
            'Traditional Game Play', 'World Dress Discussion', 'Geography Puzzle',
            'Cultural Interview', 'Food Recipe Try', 'World Music Instrument',
            'Climate Zone Map', 'Cultural Symbol Art',
        ],
        'Multilingual Basics' => [
            'French Greeting', 'Spanish Colours', 'Mandarin Numbers',
            'Korean Body Parts', 'Urdu Family Words', 'Russian Animal Names',
            'Arabic Days of Week', 'French Food Words', 'Spanish Song Sing',
            'Mandarin Stroke Order', 'Korean Hangul Intro', 'Urdu Script Trace',
            'Russian Alphabet Song', 'Multi-Language Hello', 'Language Memory Match',
            'Bilingual Story Read', 'Language Sound Compare', 'Translation Game',
            'Phrase Book Create', 'Language Show & Tell',
        ],
        'Maps & Geography' => [
            'My Neighbourhood Map', 'Continent Puzzle', 'Ocean Name Learn',
            'Compass Direction Walk', 'Globe Spin & Point', 'Treasure Map Draw',
            'Landform Model Clay', 'Capital City Match', 'Weather Map Read',
            'Country Shape Match', 'River & Mountain Label', 'Map Key Create',
            'Latitude/Longitude Intro', 'Political vs Physical Map', 'My Country Report',
            'Biome Poster', 'Cultural Region Explore', 'Scale & Distance',
            'Digital Map Navigate', 'Geography Bee Quiz',
        ],
        'Team Projects' => [
            'Group Poster Design', 'Team Presentation', 'Collaborative Story',
            'Science Fair Group Project', 'Class Garden Plant', 'Community Map Build',
            'Team Robot Build', 'Group Song Write', 'Cooperative Mural',
            'Team Challenge Timer', 'Group Research Report', 'Peer Teaching',
            'Class Newspaper', 'Team Debate Prep', 'Group Art Installation',
            'Collaborative Coding', 'Team Science Experiment', 'Group Problem Solve',
            'Class Book Write', 'Team Service Project',
        ],
        'STEM Discovery' => [
            'Rocket Launch Straw', 'Egg Drop Challenge', 'Crystal Growing',
            'Simple Robot Build', 'Catapult Design', 'Water Filter Build',
            'Solar Oven Cook', 'Bridge Weight Test', 'Electric Circuit',
            'Coding Sequence Cards', 'Weather Station Build', 'Fossil Dig',
            'Microscope Explore', 'Pendulum Swing Time', 'Gear Train Build',
            'Chemical Reaction Observe', 'Density Tower Layer', 'Paper Helicopter',
            'Maze Design Engineer', 'DNA Model Build',
        ],
        'Sensory & Motor Skills' => [
            'Fine Motor Bead Work', 'Gross Motor Obstacle', 'Balance Board Practice',
            'Sensory Path Walk', 'Finger Strength Putty', 'Hand-Eye Coordination Ball',
            'Scissor Cutting Complex', 'Clay Sculpting Detail', 'Weaving Loom',
            'Typing Practice Intro', 'Handwriting Improvement', 'Sports Skill Drill',
            'Yoga Flow Sequence', 'Dance Choreography', 'Martial Arts Move',
            'Swimming Stroke Practice', 'Gymnastics Intro', 'Ball Handling Drill',
            'Climbing Wall Session', 'Coordination Ladder Drill',
        ],
        'Scientific Method' => [
            'Hypothesis Writing', 'Observation Journal', 'Variable Identification',
            'Data Collection Sheet', 'Graph Results Bar', 'Experiment Design',
            'Control vs Variable', 'Peer Review Practice', 'Science Report Write',
            'Lab Safety Rules', 'Measurement Precision', 'Repeatable Experiment',
            'Science Fair Prep', 'Research Question Write', 'Conclusion Drawing',
            'Evidence vs Opinion', 'Scientific Tools Use', 'Classification Practice',
            'Inquiry Investigation', 'Problem-Solution Cycle',
        ],
        'Plant Life Cycles' => [
            'Seed Dissection', 'Germination Watch', 'Root Growth Window',
            'Leaf Photosynthesis', 'Flower Parts Label', 'Pollination Model',
            'Seed Dispersal Types', 'Tree Ring Count', 'Plant Timeline Draw',
            'Garden Planting', 'Composting Start', 'Water Absorption Test',
            'Light Experiment Plant', 'Soil Type Compare', 'Plant Press Herbarium',
            'Vegetable Garden', 'Fruit Seed Collection', 'Plant Disease Observe',
            'Ecosystem Model', 'Rainforest Layers',
        ],
        'Simple Machines' => [
            'Lever Experiment', 'Pulley Build Lift', 'Inclined Plane Test',
            'Wheel & Axle Explore', 'Screw Thread Observe', 'Wedge Cutting Demo',
            'Compound Machine Build', 'Force & Motion Test', 'Friction Test Slide',
            'Rube Goldberg Plan', 'Gear Ratio Explore', 'Mechanical Advantage',
            'Machine Scavenger Hunt', 'Toy Deconstruct', 'Catapult Build',
            'Zipline Design', 'Crane Model', 'Fulcrum Balance',
            'Machine Drawing Label', 'Real-World Machine Find',
        ],
        'Weather & Climate' => [
            'Weather Journal Daily', 'Cloud Type Identify', 'Rain Gauge Build',
            'Wind Vane Construct', 'Thermometer Read', 'Barometer Simple',
            'Water Cycle Model', 'Climate Zone Map', 'Severe Weather Safety',
            'Weather Forecast Report', 'Season Change Track', 'Wind Speed Measure',
            'Humidity Experiment', 'Snowflake Examine', 'Weather Station Build',
            'Climate Graph Read', 'Tornado Model Bottle', 'Rainbow Science',
            'Fog Formation Observe', 'UV Index Check',
        ],
        'Kitchen Chemistry' => [
            'Baking Soda Volcano', 'Invisible Ink Write', 'Butter Making Shake',
            'Bread Dough Rise', 'Acid/Base Test', 'Crystal Rock Candy',
            'Colour Change Indicator', 'Density Layer Drink', 'Emulsion Dressing',
            'Yeast Balloon Inflate', 'Ice Cream in Bag', 'Caramel Sugar Heat',
            'Cheese Making Simple', 'Fermentation Observe', 'Popcorn Kernel Pop',
            'Candy Chromatography', 'Egg Shell Dissolve', 'Plastic Milk Make',
            'Oobleck Non-Newtonian', 'Fruit Battery Test',
        ],
        'Block-Based Coding' => [
            'Scratch Hello World', 'Move & Turn Sprite', 'Repeat Loop Intro',
            'If-Then Condition', 'Broadcast Message', 'Animation Simple',
            'Maze Solver Code', 'Story Interactive', 'Game Score Keeper',
            'Sound & Music Code', 'Variable Intro Code', 'Cloning Sprites',
            'Random Number Code', 'Timer Countdown', 'List Data Store',
            'Platformer Game Start', 'Art Generator Code', 'Quiz App Build',
            'Multi-Sprite Interact', 'Debugging Practice',
        ],
        'Intro to Robotics' => [
            'Robot Parts Name', 'Motor & Sensor Explore', 'Line Follow Robot',
            'Obstacle Avoid Code', 'Remote Control Build', 'Sensor Reading',
            'Robot Dance Program', 'Maze Navigator', 'Pick & Place Robot',
            'Light Follow Bot', 'Sound Responsive Bot', 'Robot Race Build',
            'Arm Mechanism Build', 'Wired vs Wireless', 'Robot Ethics Discussion',
            'Sumo Robot Challenge', 'Drawing Robot', 'Sorting Robot',
            'Rescue Mission Robot', 'Robot Presentation',
        ],
        'Digital Safety' => [
            'Password Creating', 'Personal Info Privacy', 'Cyberbullying Awareness',
            'Screen Time Balance', 'Safe Browsing Rules', 'Email Safety',
            'Social Media Intro Safe', 'Stranger Danger Online', 'Digital Footprint',
            'Phishing Spot Game', 'Data Privacy Discuss', 'Healthy Tech Habits',
            'Report & Block Practice', 'Online vs Offline Friends', 'Age-Appropriate Content',
            'Download Safety', 'Camera & Photo Rules', 'Gaming Safety',
            'Digital Citizenship Pledge', 'Safety Plan Create',
        ],
        'Creative Tech Projects' => [
            'Digital Story Create', 'Animation Short Film', 'Music Remix App',
            'Photo Edit Basics', 'Blog Post Write', 'Podcast Episode Record',
            'Video Slide Show', 'Digital Art Canvas', 'Interactive Card Code',
            'QR Code Scavenger Hunt', 'Infographic Design', 'Website Page Build',
            'Stop Motion Film', 'App Prototype Sketch', 'Digital Portfolio Start',
            'E-Card Design', 'Sound Effect Create', 'Digital Comic Strip',
            'Virtual Tour Build', 'Tech Show & Tell',
        ],
        'Problem Solving with Code' => [
            'Pattern Recognition', 'Decomposition Activity', 'Algorithm Write Steps',
            'Abstraction Exercise', 'Flowchart Draw', 'Debugging Challenge',
            'Optimisation Compare', 'Logic Gate Intro', 'Binary Number Decode',
            'Sorting Algorithm Visual', 'Searching Algorithm Try', 'Recursion Simple',
            'Data Structure Intro', 'Efficiency Compare', 'Error Handling Code',
            'Test Case Writing', 'Code Review Peer', 'Pseudocode Practice',
            'Complex Problem Break', 'Hackathon Mini Challenge',
        ],
        'Python Basics' => [
            'Python Hello World', 'Variable & Type', 'Input & Print',
            'If-Else Statement', 'For Loop Count', 'While Loop Game',
            'Function Define', 'List Create & Iterate', 'Dictionary Key-Value',
            'String Manipulation', 'File Read & Write', 'Number Guessing Game',
            'Calculator Build', 'Quiz Program', 'Drawing with Turtle',
            'Simple Class Create', 'Error Handle Try-Except', 'Module Import Use',
            'Mini Project Plan', 'Code Refactor Practice',
        ],
        'Game Design' => [
            'Game Concept Sketch', 'Character Design Draw', 'Level Layout Plan',
            'Rule Set Write', 'Prototype Paper Game', 'Sprite Animation',
            'Collision Detection', 'Score System Code', 'Sound FX Add',
            'User Interface Design', 'Difficulty Levels', 'Story Integration',
            'Beta Test & Feedback', 'Bug Fix Session', 'Multiplayer Concept',
            'Game Review Write', 'Genre Study', 'Mechanics Analysis',
            'Final Polish & Release', 'Game Jam Participation',
        ],
        'Web Literacy' => [
            'HTML Structure Intro', 'Tags & Elements', 'CSS Styling Basics',
            'Image & Link Add', 'Page Layout Build', 'Responsive Design Intro',
            'Web Accessibility', 'Domain & Hosting Concept', 'Browser Inspector Use',
            'Form Elements', 'Colour Theory Web', 'Typography Web Basics',
            'Navigation Menu Build', 'Web Safety & HTTPS', 'Content Management',
            'SEO Basics', 'Web Performance', 'Version Control Intro',
            'Portfolio Page Build', 'Web Project Present',
        ],
        'Computational Thinking' => [
            'Pattern Sequence Identity', 'Problem Decompose Steps', 'Abstract Model Build',
            'Algorithm Efficiency', 'Data Representation', 'Logic Puzzle',
            'Simulation Concept', 'Automation Idea', 'System Thinking',
            'Parallel Process Concept', 'Feedback Loop Identify', 'Decision Tree Draw',
            'State Machine Simple', 'Optimise Route', 'Modelling Real World',
            'Complex System Map', 'Information Hierarchy', 'Process Flow Chart',
            'Design Thinking Apply', 'Innovation Challenge',
        ],
        'Mini Hackathon' => [
            'Team Formation', 'Problem Statement Pick', 'Research Phase Sprint',
            'Idea Brainstorm', 'MVP Plan', 'Sprint Code Session 1',
            'Sprint Code Session 2', 'Design Implementation', 'Testing Phase',
            'Bug Fix Sprint', 'Presentation Prep', 'Demo Day Rehearse',
            'Feedback Collection', 'Iterate & Improve', 'Documentation Write',
            'Project Poster Create', 'Peer Code Review', 'Reflection Write',
            'Awards & Recognition', 'Next Steps Plan',
        ],
        'Logic & Reasoning' => [
            'Sudoku Intro', 'Logic Grid Puzzle', 'Deductive Reasoning Card',
            'Inductive Reasoning Game', 'Syllogism Practice', 'Truth Table Build',
            'Venn Diagram Logic', 'Riddle Challenge', 'Lateral Thinking Puzzle',
            'Chess Strategy Intro', 'If-Then-Else Logic', 'Fallacy Identification',
            'Argument Structure', 'Analogy Complete', 'Sequence Prediction',
            'Pattern Detection Complex', 'Brain Teaser Challenge', 'Logic Circuit Design',
            'Probability Reason', 'Evidence Evaluation',
        ],
        'Philosophy for Kids' => [
            'What Is Fair Discussion', 'Thought Experiment Simple', 'Ethics Story Discuss',
            'Socratic Question Practice', 'Happiness Definition Explore', 'Justice Concept',
            'Freedom vs Rules', 'Mind & Body Question', 'Beauty in Nature Discuss',
            'Truth vs Lie Ethics', 'Right vs Wrong Scenario', 'Empathy Deep Dive',
            'Purpose of School Discuss', 'Friendship Philosophy', 'Change vs Permanence',
            'Animal Rights Discussion', 'Environment Ethics', 'Identity Question',
            'Dream Meaning Explore', 'Big Questions Journal',
        ],
        'Advanced Maths Puzzles' => [
            'Magic Square Solve', 'Number Pattern Complex', 'Fraction Visual Model',
            'Algebra Letter Intro', 'Geometry Angle Measure', 'Area Perimeter Calculate',
            'Ratio Introduction', 'Decimal Place Value', 'Order of Operations',
            'Word Problem Multi-Step', 'Prime Number Sieve', 'Factor Tree Build',
            'Coordinate Grid Plot', 'Symmetry Rotation', 'Data Analysis Graph',
            'Mean Median Mode', 'Probability Experiment', 'Volume Capacity',
            'Time Zone Calculate', 'Roman Numeral Decode',
        ],
        'Debate & Argumentation' => [
            'Debate Format Intro', 'For & Against List', 'Evidence Finding',
            'Rebuttal Practice', 'Opening Statement Write', 'Audience Persuasion',
            'Logical Fallacy Spot', 'Cross Examination Try', 'Emotional Appeal vs Logic',
            'Current Events Debate', 'Structured Debate Round', 'Active Listening Debate',
            'Compromise Finding', 'Counterargument Build', 'Closing Statement',
            'Impromptu Debate', 'Written Argument Essay', 'Peer Feedback Debate',
            'Parliamentary Style Intro', 'Debate Reflection Journal',
        ],
        'Research Skills' => [
            'Question Formulation', 'Source Evaluation', 'Library Catalogue Use',
            'Note-Taking Strategy', 'Bibliography Format', 'Primary vs Secondary Source',
            'Internet Research Safe', 'Interview for Research', 'Survey Design',
            'Data Organisation', 'Outline Writing', 'Paraphrasing Practice',
            'Quote Integration', 'Fact vs Opinion', 'Research Presentation',
            'Peer Review Research', 'Research Ethics', 'Infographic from Research',
            'Annotated Bibliography', 'Research Proposal Write',
        ],
        'Leadership Foundations' => [
            'Leader vs Boss Discuss', 'Communication Exercise', 'Team Motivation',
            'Decision Making Process', 'Delegation Practice', 'Conflict Mediation',
            'Vision Statement Write', 'Accountability Partner', 'Servant Leadership',
            'Feedback Giving Practice', 'Time Management Plan', 'Goal Setting SMART',
            'Public Speaking Short', 'Influence vs Authority', 'Ethics in Leadership',
            'Historical Leader Study', 'Leadership Journal', 'Meeting Facilitation',
            'Presentation Skills', 'Leadership Reflection',
        ],
        'Entrepreneurship Basics' => [
            'Business Idea Brainstorm', 'Problem-Solution Fit', 'Customer Interview',
            'Revenue Model Simple', 'Cost Calculation', 'Elevator Pitch Write',
            'Logo & Brand Design', 'Market Research Survey', 'Competitor Analysis',
            'Prototype Build', 'Sales Practice Role-Play', 'Financial Literacy Intro',
            'Advertisement Create', 'Product Pricing', 'Business Plan Simple',
            'Supply & Demand Game', 'Social Enterprise Concept', 'Profit vs Cost',
            'Shark Tank Presentation', 'Business Reflection',
        ],
        'Public Speaking' => [
            'Self Introduction Speech', 'Show & Tell Present', 'Story Telling Aloud',
            'Impromptu Speech Timer', 'Visual Aid Use', 'Voice Projection Exercise',
            'Eye Contact Practice', 'Gesture & Body Language', 'Handling Nervousness',
            'Audience Engagement', 'Persuasive Speech', 'Informative Speech',
            'Debate Participation', 'Group Presentation', 'Feedback Reception',
            'Speech Structure Outline', 'Toastmasters Style', 'Video Record & Review',
            'Speech Competition Prep', 'Graduation Speech Draft',
        ],
        'Global Citizenship' => [
            'UN Goals for Kids', 'Cultural Exchange Activity', 'World Problem Identify',
            'Charity Project Plan', 'Environmental Action', 'Peace Message Write',
            'Human Rights Intro', 'Fair Trade Concept', 'Global Current Events',
            'Pen Pal Exchange', 'Diversity Celebration', 'Community Service Plan',
            'Global Food Security', 'Water Conservation', 'Climate Action Steps',
            'Migration Story Read', 'Global Health Awareness', 'Digital Global Connect',
            'Advocacy Letter Write', 'Global Citizen Pledge',
        ],
        'STEM Capstone Project' => [
            'Project Topic Select', 'Research Deep Dive', 'Hypothesis Form',
            'Experiment Design Plan', 'Materials & Methods', 'Data Collection Phase',
            'Data Analysis Phase', 'Graph & Visualise', 'Conclusion Write',
            'Peer Review Session', 'Poster Board Create', 'Oral Presentation Prep',
            'Demo Build', 'Documentation Complete', 'Reflection Write',
            'Science Fair Submit', 'Community Presentation', 'Video Summary Record',
            'Cross-Discipline Connect', 'Future Research Ideas',
        ],
    ];

    /** Valid activity types matched to module themes */
    private array $typeMap = [
        'sensory' => ['matching', 'outdoor', 'experiment'],
        'visual' => ['video', 'experiment', 'drawing'],
        'music' => ['music', 'video', 'story'],
        'movement' => ['outdoor', 'video', 'experiment'],
        'bonding' => ['story', 'music', 'outdoor'],
        'motor' => ['puzzle', 'drawing', 'experiment'],
        'etiquette' => ['story', 'quiz', 'matching'],
        'quran' => ['story', 'music', 'quiz', 'drawing'],
        'arabic' => ['tracing', 'quiz', 'matching', 'story'],
        'culture' => ['story', 'drawing', 'video', 'quiz'],
        'life' => ['quiz', 'matching', 'outdoor', 'story'],
        'creative' => ['drawing', 'music', 'experiment', 'story'],
        'literacy' => ['tracing', 'story', 'quiz', 'matching'],
        'numeracy' => ['puzzle', 'quiz', 'matching', 'experiment'],
        'science' => ['experiment', 'video', 'quiz', 'outdoor'],
        'social' => ['story', 'quiz', 'matching', 'outdoor'],
        'coding' => ['puzzle', 'quiz', 'experiment', 'coding'],
        'robotics' => ['experiment', 'coding', 'video'],
        'stem' => ['experiment', 'coding', 'puzzle', 'video'],
        'leadership' => ['story', 'quiz', 'outdoor', 'video'],
    ];

    /** Subject mapping from module title keywords */
    private function guessSubject(string $moduleTitle): string
    {
        $lower = strtolower($moduleTitle);
        $map = [
            'sensory' => 'sensory', 'touch' => 'sensory', 'visual' => 'sensory',
            'sound' => 'sensory', 'music' => 'art',
            'tummy' => 'motor', 'movement' => 'motor', 'walking' => 'motor',
            'balance' => 'motor', 'motor' => 'motor', 'grasp' => 'motor',
            'bonding' => 'social', 'social' => 'social', 'sharing' => 'social',
            'imitation' => 'social',
            'etiquette' => 'etiquette', 'personality' => 'etiquette', 'royal' => 'etiquette',
            'quran' => 'quran', 'islamic' => 'quran',
            'arabic' => 'arabic',
            'culture' => 'cultural', 'world' => 'cultural', 'multilingual' => 'cultural',
            'global' => 'cultural',
            'life skill' => 'social', 'routine' => 'social', 'independence' => 'social',
            'creative' => 'art', 'drawing' => 'art', 'painting' => 'art',
            'arts' => 'art', 'craft' => 'art',
            'word' => 'language', 'communication' => 'language', 'first word' => 'language',
            'alphabet' => 'literacy', 'phonics' => 'literacy', 'reading' => 'literacy',
            'writing' => 'literacy', 'storytelling' => 'literacy', 'rhyme' => 'literacy',
            'poetry' => 'literacy', 'story' => 'literacy',
            'counting' => 'numeracy', 'number' => 'numeracy', 'math' => 'numeracy',
            'pattern' => 'numeracy', 'colour' => 'numeracy',
            'sorting' => 'numeracy', 'shape' => 'numeracy',
            'cause' => 'stem', 'effect' => 'stem', 'nature' => 'science',
            'science' => 'science', 'scientific' => 'science', 'plant' => 'science',
            'machine' => 'science', 'weather' => 'science', 'climate' => 'science',
            'kitchen' => 'science', 'chemistry' => 'science',
            'stem' => 'stem', 'discovery' => 'stem', 'capstone' => 'stem',
            'coding' => 'coding', 'python' => 'coding', 'code' => 'coding',
            'block' => 'coding', 'scratch' => 'coding', 'web' => 'coding',
            'robotics' => 'robotics', 'robot' => 'robotics',
            'digital' => 'stem', 'safety' => 'social', 'tech' => 'coding',
            'game' => 'coding', 'hackathon' => 'coding', 'computation' => 'coding',
            'logic' => 'stem', 'reasoning' => 'stem', 'philosophy' => 'social',
            'debate' => 'literacy', 'research' => 'literacy',
            'leader' => 'social', 'entrepreneur' => 'social', 'public speak' => 'literacy',
            'imagination' => 'art', 'imaginative' => 'art',
            'emotion' => 'social', 'self-regulation' => 'social',
            'map' => 'cultural', 'geography' => 'cultural',
            'team' => 'social',
        ];

        foreach ($map as $keyword => $subject) {
            if (str_contains($lower, $keyword)) {
                return $subject;
            }
        }

        return 'literacy';
    }

    private function guessTypes(string $moduleTitle): array
    {
        $lower = strtolower($moduleTitle);
        foreach ($this->typeMap as $keyword => $types) {
            if (str_contains($lower, $keyword)) {
                return $types;
            }
        }

        return ['quiz', 'story', 'matching', 'drawing'];
    }

    public function run(): void
    {
        $courses = Course::with('modules')->get();

        foreach ($courses as $course) {
            foreach ($course->modules as $module) {
                $titles = $this->templates[$module->title] ?? null;
                if (! $titles) {
                    continue;
                }

                $subject = $this->guessSubject($module->title);
                $types = $this->guessTypes($module->title);

                foreach ($titles as $order => $title) {
                    $type = $types[$order % count($types)];
                    $activity = Activity::create([
                        'title' => $title,
                        'description' => "A fun {$type} activity for ages {$course->age_min}–{$course->age_max}: {$title}.",
                        'age_min' => $course->age_min,
                        'age_max' => $course->age_max,
                        'subject' => $subject,
                        'activity_type' => $type,
                        'duration_minutes' => rand(5, 25),
                        'difficulty' => ['easy', 'medium', 'medium', 'hard'][rand(0, 3)],
                        'language' => 'en',
                        'is_free' => $order < 7,
                        'emoji' => $course->emoji,
                        'materials_needed' => json_encode(['Paper', 'Colours']),
                        'learning_objectives' => json_encode(["Develop {$subject} skills", "Practice {$type} activities"]),
                    ]);

                    $activity->modules()->attach($module->id, ['order' => $order + 1]);
                }
            }
        }
    }
}
