<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;

/**
 * Emotional Regulation Seeder
 *
 * Research-backed activities covering:
 * - Zone of Regulation framework (Kuypers, 2011)
 * - Co-regulation (caregiver-led calming)
 * - Self-regulation milestones by age tier
 * - Polyvagal theory (bottom-up interventions: breath, movement, rhythm)
 * - Mindfulness-based stress reduction adapted for children
 * - Bibliotherapy (using books to process emotions)
 * - Islamic emotional teachings (sabr, shukr, forgiveness, tawakkul)
 */
class EmotionalRegulationSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('💚 Seeding Emotional Regulation activities...');

        foreach ($this->activities() as $data) {
            Activity::create($data);
        }

        $this->command->info('✅ Emotional Regulation activities seeded: ' . count($this->activities()));
    }

    private function activities(): array
    {
        $base = [
            'language'   => 'en',
            'is_free'    => false,
            'subject'    => 'emotional_regulation',
        ];

        return array_map(fn($a) => array_merge($base, $a), [

            // ═══════════════════════════════════════════════════════════════
            // BABIES (0–12 months) — Co-regulation, Primary Soothing
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'The Soothing Hold — Co-Regulation for Babies',
                'description'         => 'The foundational co-regulation technique for infants: a specific calming hold where the parent\'s regulated nervous system helps regulate the baby\'s. Based on polyvagal theory — rhythmic containment signals safety to the baby\'s developing brain.',
                'instructions'        => "1. When baby is distressed, remain calm yourself first (take three slow breaths).\n2. Pick baby up and hold them securely against your chest — baby's ear over your heartbeat.\n3. Begin slow, rhythmic swaying: one full sway per second.\n4. Hum or sing softly — a low, repetitive sound.\n5. Maintain this for 3-5 minutes or until baby\'s breathing slows.\n6. Then sit and maintain warmth until baby is fully settled.\nNote: A regulated parent is the most powerful regulation tool for a baby.",
                'instructions_for_parent' => 'Before you start, take 3 slow diaphragmatic breaths yourself. Your nervous system directly affects your baby\'s. If you are stressed, your baby will feel it. Settle yourself first. This is not optional — it is the intervention.',
                'activity_type'       => 'interactive',
                'age_min'             => 0,
                'age_max'             => 12,
                'duration_minutes'    => 10,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => ['Never shake a baby', 'Ensure a firm but gentle hold', 'If baby is unresponsive or breathing difficulty — seek medical attention immediately'],
                'adaptations'         => ['variation' => 'For a very distressed baby: try skin-to-skin contact on a warm surface, or a warm bath held securely (for older babies)'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'sensory'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '🤗',
            ],
            [
                'title'               => 'Attuned Face-to-Face — Emotional Mirroring',
                'description'         => 'Based on Stern\'s theory of affect attunement. Parent mirrors baby\'s facial expressions and emotional tone, then gradually shifts toward a calmer or more joyful expression — demonstrating bidirectional emotional influence. This builds the baby\'s emotional reading skills.',
                'instructions'        => "1. Sit with baby face-to-face, close enough to make eye contact.\n2. Watch baby\'s expression. Match it: if they smile, you smile. If they look surprised, show surprise.\n3. After mirroring, very slowly shift your expression to calm and soft.\n4. Wait and watch — does baby follow you toward calm?\n5. For happy play: mirror excitement, then add a new expression and see if baby copies you.\n6. Talk through it: 'I see you! You look happy!'",
                'instructions_for_parent' => 'This is one of the most powerful connection activities you can do. Every face-to-face session wires new emotional understanding into your baby\'s brain. Make it a daily practice — even 5 minutes counts.',
                'activity_type'       => 'interactive',
                'age_min'             => 1,
                'age_max'             => 9,
                'duration_minutes'    => 8,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'Use a mirror together — let baby see both their face and yours side by side'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'language', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '😊',
            ],
            [
                'title'               => 'This Is How I Feel — Baby Emotion Naming',
                'description'         => 'Research shows that naming emotions (emotional labelling or "name it to tame it") reduces the intensity of negative emotions in the brain even in pre-verbal infants. Parents who consistently name their baby\'s feelings build emotional intelligence from birth.',
                'instructions'        => "1. During everyday moments — nappy change, feeding, waking — narrate baby\'s likely emotional state.\n2. Use simple, clear emotion words with matching expression: 'You\'re hungry — that feels uncomfortable.'\n3. When baby is upset: 'You\'re frustrated! It\'s okay to feel frustrated.'\n4. When baby is happy: 'Oh, you are SO happy right now! Look at that smile!'\n5. When baby is tired: 'You feel sleepy. Your body is asking for rest.'\n6. Do this consistently — every day, many times a day.",
                'instructions_for_parent' => 'You cannot over-do emotional labelling. Every time you name an emotion, you grow your baby\'s emotional vocabulary and their capacity to regulate. This is the single highest-leverage emotional activity you can do with a baby.',
                'activity_type'       => 'interactive',
                'age_min'             => 0,
                'age_max'             => 12,
                'duration_minutes'    => 5,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'Add a facial expression manual — print 6 clear emotion faces and refer to them while talking to baby'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '💬',
            ],

            // ═══════════════════════════════════════════════════════════════
            // TODDLERS (12–36 months) — Emotion Recognition, Big Feelings
            // Management, Tantrums, Calming Strategies
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Feelings Faces Board',
                'description'         => 'A physical or digital emotion chart placed at child height. Toddlers point to how they feel throughout the day. This daily ritual builds emotion vocabulary, normalises talking about feelings, and gives parents early warning of emotional needs.',
                'instructions'        => "1. Create or print a feelings chart with 6–8 faces and labels: happy, sad, angry, scared, surprised, tired, silly, worried.\n2. Place it at child's eye level.\n3. Morning: 'How are you feeling today? Can you show me on the chart?'\n4. Child points or parent points and names.\n5. Revisit at lunch and bedtime.\n6. When a big feeling happens: 'Wow, that looks like the angry face. Is that right?'\n7. Never judge the feeling — only validate it.",
                'instructions_for_parent' => 'Validation does NOT mean you approve of the behaviour. It means you acknowledge the feeling. "I understand you feel angry" is different from "It\'s okay to hit." Feelings are always valid. Actions sometimes need redirection.',
                'activity_type'       => 'play',
                'age_min'             => 18,
                'age_max'             => 48,
                'duration_minutes'    => 5,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with only 3 faces: happy, sad, angry', 'harder' => 'Ask child to draw their own face for each feeling'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'language', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '😄',
            ],
            [
                'title'               => 'Burst-and-Settle Tantrum Protocol',
                'description'         => 'A structured parent response to toddler tantrums based on polyvagal theory and PACE (Dan Hughes). Not an activity the child does, but a precise parent-led intervention during tantrums that shortens their duration and strengthens the child-parent relationship.',
                'instructions'        => "Phase 1 — SAFETY (1 min): Stay near. Do not leave. Do not lecture or reason. Say calmly: 'I\'m right here.'\nPhase 2 — WAIT (2–3 min): Allow the storm to pass. A tantrum is a neurological storm — it must run its course.\nPhase 3 — RECONNECT (as storm fades): Get down to child\'s level. Reach out with warmth. 'That was really big, wasn\'t it?' \nPhase 4 — MOVE (if still flooding): Offer a change of scene, a glass of water, or a sensory anchor (a favourite texture or smell).\nPhase 5 — RESTORE (once calm): Brief, warm connection. 'I love you even when feelings are big.' No lecture now.",
                'instructions_for_parent' => 'WHAT NOT TO DO during a tantrum: Don\'t reason (the frontal lobe is offline). Don\'t punish (it extends the tantrum). Don\'t shame ("stop being a baby"). Don\'t walk away unless YOU are at risk of losing control. WHAT TO DO: Be the calm — your nervous system is the medicine.',
                'activity_type'       => 'interactive',
                'age_min'             => 18,
                'age_max'             => 42,
                'duration_minutes'    => 15,
                'difficulty'          => 'medium',
                'mess_level'          => 'low',
                'safety_warnings'     => ['Never restrain a child in anger', 'Ensure environment is physically safe before waiting out tantrum (no sharp edges etc.)'],
                'adaptations'         => ['variation' => 'If tantrums occur in public: use a quiet corner, keep voice low, use fewer words — "I\'m here" is enough'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '🌊',
            ],
            [
                'title'               => 'The Calm Down Corner — Child-Led Safe Space',
                'description'         => 'A child-designed corner of the room filled with comforting objects where they can go voluntarily when overwhelmed. Different from a "time-out" (punitive) — this is a self-regulated safe space that the child owns and chooses to use. Builds autonomy and self-regulation simultaneously.',
                'instructions'        => "1. Together with child, choose a corner of a room.\n2. Add: one soft toy, one sensory item (putty, smooth stone), calming colours, maybe a picture of something they love.\n3. Practice going there together when CALM: 'This is your peace corner. It\'s a happy place.'\n4. During distress, offer (never force): 'Would you like to go to your peace corner?'\n5. Never use it as punishment.\n6. Parent can visit the corner too, modelling self-regulation: 'I\'m going to my peace spot because I need to calm down.'",
                'instructions_for_parent' => 'The Calm Down Corner only works if it has been experienced positively before a crisis. Do not introduce it during a tantrum. Practice it during calm moments so the child has a positive association with it.',
                'activity_type'       => 'play',
                'age_min'             => 24,
                'age_max'             => 72,
                'duration_minutes'    => 20,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'A "calm kit" in a box (carried anywhere) can replicate this for travel or school settings'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'sensory'],
                'materials_cost'      => 'low',
                'parent_involvement'  => 'guided',
                'emoji'               => '🏠',
            ],

            // ─── Islamic Foundations of Emotional Regulation ────────────
            [
                'title'               => 'Sabr Breathing — Patience Practice (Toddler & Preschool)',
                'description'         => 'Connecting the Islamic concept of sabr (صَبْر — patience) to a simple breathing exercise. When a child wants something and must wait, they practice "sabr breaths" — this reframes waiting as a noble, spiritual act rather than a punishment.',
                'instructions'        => "1. When child wants something immediately, kneel down and say: 'Let\'s practice our sabr breaths while we wait.'\n2. Breathe in together, slowly, for 3 counts.\n3. Breathe out slowly for 3 counts.\n4. Do 3 rounds.\n5. Say together: 'Allah loves people who have sabr.'\n6. Praise: 'You showed such beautiful sabr just now!'\n7. Deliver the item/answer after the breathing if appropriate.",
                'instructions_for_parent' => 'This is not a distraction technique — it is character formation. Connect physical calming to Islamic virtue daily. Children who understand WHY they are being patient (because it pleases Allah and grows their character) develop intrinsic motivation for regulation.',
                'activity_type'       => 'mindfulness',
                'age_min'             => 24,
                'age_max'             => 72,
                'duration_minutes'    => 5,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'For older children (4-6): introduce the du\'a for patience and teach them to say it during difficult moments'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'spiritual'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '🤲',
            ],

            // ═══════════════════════════════════════════════════════════════
            // PRESCHOOL (36–72 months) — Zones of Regulation, Breathing
            // Tools, Emotion Coaching, Empathy Building
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Zones of Regulation — Introduction (Ages 3–6)',
                'description'         => 'Based on Leah Kuypers\' Zones of Regulation framework — a widely-used evidence-based approach in occupational therapy and schools. Children learn 4 coloured zones representing states of arousal and emotional regulation.',
                'instructions'        => "Introduce one zone per week:\nBLUE ZONE (Week 1): 'Slow and sad — like a turtle going slowly. When do we feel blue?' (Sleepy, sad, sick, bored.) Draw blue turtle together.\nGREEN ZONE (Week 2): 'Just right — like a happy frog ready to learn and play!'\nYELLOW ZONE (Week 3): 'Alert but a bit wobbly — like a bouncy kangaroo. Excited, worried, silly.'\nRED ZONE (Week 4): 'Big and intense — like a volcano! Angry, terrified, out of control.'\nWeekly check-ins: 'What zone are you in right now?'",
                'instructions_for_parent' => 'Once the four zones are established, you can start saying "looks like you\'re in the yellow zone — what could help you get back to green?" This gives children a vocabulary for self-monitoring that is enormously powerful.',
                'activity_type'       => 'drawing',
                'age_min'             => 36,
                'age_max'             => 84,
                'duration_minutes'    => 20,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with just two zones: Calm (green) and Big Feelings (red); expand once those are solid', 'harder' => 'Add a "tools" chart for each zone: what strategies live in the green zone? the yellow zone?'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🗺️',
            ],
            [
                'title'               => 'Belly Breathing with a Stuffed Animal',
                'description'         => 'Teaching diaphragmatic breathing — the most reliable immediate intervention for reducing physiological arousal. Children place a stuffed animal on their belly; it rises on the inhale and falls on the exhale, providing visual biofeedback.',
                'instructions'        => "1. Child lies on their back.\n2. Place a small stuffed animal on their belly button.\n3. Say: 'Let\'s give (Teddy) a little ride!'\n4. Breathe in through the nose — Teddy goes UP.\n5. Breathe out slowly through the mouth — Teddy comes DOWN.\n6. Do 5 slow rounds. \n7. After: 'How does your body feel now?' \n8. Practice this when calm so it becomes automatic in stress.",
                'instructions_for_parent' => 'This activity works best when practiced daily during calm times. Children cannot learn new skills in the middle of a crisis — but a well-practiced skill will activate automatically when needed. 5 minutes a day of practice saves hours of dysregulation.',
                'activity_type'       => 'mindfulness',
                'age_min'             => 36,
                'age_max'             => 72,
                'duration_minutes'    => 8,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Parent places their hand on child\'s belly instead of a toy', 'harder' => 'Progress to "5-5-5" breathing: in for 5, hold for 5, out for 5 — a more powerful calming technique'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'gross_motor'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '😮‍💨',
            ],
            [
                'title'               => 'Emotion Detective — Reading Faces & Situations',
                'description'         => 'Building emotional empathy through detective work. Children observe pictures or scenes (from books, magazines, or paused video) and deduce how characters are feeling and why. This trains Theory of Mind and empathy simultaneously.',
                'instructions'        => "1. Use a picture book, a magazine, or a paused video clip.\n2. Point to a person/character: 'Look at their face. What do you think they are feeling?'\n3. Accept all responses with curiosity: 'Interesting! What makes you think that?'\n4. Offer your read: 'I think they might feel... because I can see...'\n5. Ask: 'Has something like this ever happened to you? How did YOU feel?'\n6. Key: validate the character\'s feeling first before discussing the situation.",
                'instructions_for_parent' => 'Use this activity with books and movies your child already loves — they will be highly motivated to understand characters they care about. Fiction is the most effective empathy training tool we have.',
                'activity_type'       => 'story',
                'age_min'             => 36,
                'age_max'             => 84,
                'duration_minutes'    => 15,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use simple, single-page illustrations with very clear emotional expressions', 'harder' => 'Use scenes with ambiguous emotions — where multiple interpretations are valid — and discuss why people can feel differently about the same event'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'language', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🔍',
            ],
            [
                'title'               => 'Feelings Artwork — Expressing Emotions Through Colour',
                'description'         => 'Children choose colours that "feel like" their current emotion and create abstract artwork. This non-verbal expression is therapeutic and builds emotional vocabulary by linking physical sensation, colour, and emotion word.',
                'instructions'        => "1. Place paints, crayons, or pens available.\n2. Ask: 'How are you feeling right now?'\n3. Ask: 'If your feeling was a colour, what colour would it be?'\n4. Invite child to create — abstract, not representational: 'Just paint how you feel.'\n5. Ask questions: 'Is it big or small? Fast or slow? Loud or quiet?'\n6. Let child title the artwork with their emotion.\n7. Display it: feelings deserve to be seen.",
                'instructions_for_parent' => 'Do not correct or redirect the child\'s colour choices. A child who paints happiness as black is not "wrong" — they are showing you their inner world. Receive it with curiosity, not correction. This art is emotionally honest.',
                'activity_type'       => 'drawing',
                'age_min'             => 36,
                'age_max'             => 84,
                'duration_minutes'    => 20,
                'difficulty'          => 'easy',
                'mess_level'          => 'medium',
                'safety_warnings'     => ['Ensure all paints are non-toxic'],
                'adaptations'         => ['easier' => 'Offer only 3 colours and have child say what each one feels like before starting', 'harder' => 'Create a "feelings colour dictionary" together — building a personal emotional vocabulary map over weeks'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'creative_arts', 'fine_motor'],
                'materials_cost'      => 'low',
                'parent_involvement'  => 'guided',
                'emoji'               => '🎨',
            ],
            [
                'title'               => 'Emotion Puppet Theatre',
                'description'         => 'Using simple finger puppets or sock puppets, children act out emotional scenarios and practice different responses. Puppet play reduces the intensity of emotional situations and allows children to safely rehearse handling big feelings.',
                'instructions'        => "1. Make simple sock puppets or use finger puppets.\n2. Set up a scenario: 'This puppet is feeling left out at playtime. What happens?'\n3. Let child play out the story with both puppets.\n4. Gently guide: 'What could the other puppet do to help?'\n5. Introduce a third puppet as a 'wise helper.'\n6. After: 'Has this ever happened to you? What did you do?'\n7. Role-play 3–4 common emotional scenarios.",
                'instructions_for_parent' => 'Common scenarios to explore: being excluded, losing a game, a sibling taking a toy, feeling worried about a new place, feeling proud of something. Puppets allow children to explore these without the emotional charge of "this happened to me."',
                'activity_type'       => 'creative_play',
                'age_min'             => 36,
                'age_max'             => 72,
                'duration_minutes'    => 20,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use only two puppets (self and other) and one simple scenario', 'harder' => 'Child leads the entire theatre session and creates their own emotional storylines'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'language', 'creative_arts', 'executive_function'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🎭',
            ],

            // ─── Islamic Emotional Regulation (Preschool) ───────────────
            [
                'title'               => 'Alhamdulillah Gratitude Moments — Shukr Practice',
                'description'         => 'Building a daily shukr (شُكْر — gratitude) habit. Research shows gratitude practice measurably increases wellbeing, reduces negative emotional reactivity, and builds a positive emotional baseline. Rooted in the Islamic understanding that shukr attracts more blessings.',
                'instructions'        => "1. Choose a consistent time: after breakfast, at Maghrib, or before bed.\n2. Ask: 'What is one thing you are thankful for today?'\n3. Say 'Alhamdulillah' together, with meaning.\n4. Parent also shares their gratitude — modelling the practice.\n5. Over weeks, expand: 'What about something for your body? For your family? For something in nature?'\n6. Consider a visual gratitude jar — write/draw each on paper and add to the jar.\n7. Read from the jar together on days when feelings are heavy.",
                'instructions_for_parent' => 'The most powerful element of this practice is YOUR participation. When your child sees YOU practising genuine gratitude — not performed, but real — they internalise it as a way of life, not just an activity.',
                'activity_type'       => 'mindfulness',
                'age_min'             => 36,
                'age_max'             => 120,
                'duration_minutes'    => 5,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'Add Quranic context (14:7): "If you are grateful, I will give you more" — children respond to this promise deeply'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'spiritual', 'metacognition'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '✨',
            ],
            [
                'title'               => 'Anger Is Not Shaytaan\'s Friend — Managing Anger Islamically',
                'description'         => 'Using the hadith of the Prophet ﷺ about anger (sit if standing, lie down if sitting, make wudu if angry) to give children both a spiritual framework and a practical physical intervention for anger. Physical positions change the body\'s stress chemistry.',
                'instructions'        => "1. Teach the concept: 'When we are angry, our body wants to push and shout. But the Prophet ﷺ taught us something special.'\n2. Share: 'If you feel huge anger — first, sit down if you are standing.'\n3. 'If that doesn\'t help, lie down on your back.'\n4. 'Say A\'udhu billahi min ash-shaytaan ir-rajeem.'\n5. Practice the sequence: stand → sit → lie → breathe → say the words.\n6. Connect: 'Anger is a test from Allah — and you can pass it!'",
                'instructions_for_parent' => 'Model this yourself. When YOU feel angry, say aloud: "I\'m feeling angry. I\'m going to sit down and make dua." This is perhaps the most powerful thing you can do — seeing a parent regulate their own anger Islamically is transformative for a child.',
                'activity_type'       => 'mindfulness',
                'age_min'             => 36,
                'age_max'             => 84,
                'duration_minutes'    => 10,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'Make a simple "anger card" for the child\'s room with the three positions illustrated, to refer to during moments of anger'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'spiritual'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🛡️',
            ],
            [
                'title'               => 'The Worry Tree — Externalising Anxiety',
                'description'         => 'A visual anxiety management technique for preschoolers. Children draw a tree and write/draw their worries on leaves. Then, for each worry, they decide: "Can I do something about this? → Do it action." or "Can I NOT do anything? → Let the leaf blow away." Teaches differentiating action from acceptance.',
                'instructions'        => "1. Together, draw a large tree on paper.\n2. Say: 'Everyone has worries. Let\'s put our worries on the tree.'\n3. Child names worries — parent draws/writes each on a leaf.\n4. For each leaf: 'Can you do something about this worry?'\n5. → YES: write the action on the leaf stem. Child commits to doing it.\n6. → NO: say 'Then we give this one to Allah.' Physically tear off the leaf, or scrunch it.\n7. 'Tawakkul means trusting Allah with the things we cannot control.'",
                'instructions_for_parent' => 'The tearing or removing of the "no-action" worry leaves is important — it is a physical action that corresponds to letting go. Do not skip this step. The body needs to participate in release, not just the mind.',
                'activity_type'       => 'drawing',
                'age_min'             => 48,
                'age_max'             => 84,
                'duration_minutes'    => 20,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use pictures instead of words for very young children; only process 1–2 worries per session', 'harder' => 'Add a journaling component: child writes 3 possible actions for each "can do something" worry and circles the best one'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🌳',
            ],

            // ═══════════════════════════════════════════════════════════════
            // SCHOOL (72–120 months) — Advanced Self-Regulation, Conflict
            // Resolution, Mindfulness, Growth Mindset, Metacognition
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Body Scan Mindfulness (Ages 6–10)',
                'description'         => 'A full body scan meditation adapted for children. Systematically bringing attention through the body from feet to head builds interoceptive awareness — the ability to notice and interpret signals from inside the body. This is the foundation of emotional self-regulation.',
                'instructions'        => "1. Child lies comfortably on their back.\n2. Begin: 'Take three slow breaths and let your body relax.'\n3. Guide gently through the body, staying 15–20 seconds on each area:\n   'Notice your feet. How do they feel? Heavy? Light? Warm?'\n   'Now notice your legs... your belly... your chest... your hands...'\n   'Now your face — is it relaxed? Can you soften your jaw?'\n4. End: 'How does your whole body feel now?'\n5. 10–12 minutes total.",
                'instructions_for_parent' => 'Do this body scan yourself regularly so you experience its effects. When children ask "why are we doing this?", share genuinely: "I feel calmer after. It helps me notice when I\'m stressed before it becomes too big." Personal testimony is powerful.',
                'activity_type'       => 'mindfulness',
                'age_min'             => 72,
                'age_max'             => 120,
                'duration_minutes'    => 12,
                'difficulty'          => 'medium',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'For restless children: pair each body part with a physical action first (wiggle toes, clap hands) before the quiet scan', 'harder' => 'Add a visualisation element: as you scan each area, imagine pouring warm golden light into that body part'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'metacognition'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🫁',
            ],
            [
                'title'               => 'Growth Mindset Failure Debrief',
                'description'         => 'A structured conversation protocol following any failure, mistake, or setback. Rather than minimising ("it\'s fine!") or catastrophising ("that\'s terrible"), this protocol validates, analyses, and builds forward momentum. Trains metacognition and a growth mindset simultaneously.',
                'instructions'        => "Use the 5-step LEARN protocol:\nL — Label the feeling: 'What are you feeling right now? Name it.'\nE — Explore it: 'Tell me what happened.'\nA — Accept it: 'It makes complete sense you feel ___. That was hard.'\nR — Reframe: 'What can we learn from this?'\nN — Next: 'What\'s one thing you\'ll try differently next time?'\n\nEnd EVERY debrief with: 'I\'m proud of you for trying. That\'s what matters to me.'",
                'instructions_for_parent' => 'This protocol works for you too. Model it on your own failures in front of your child: "I made a mistake today. I felt frustrated. But I learned that next time I should... " This is the most powerful growth-mindset lesson you can teach.',
                'activity_type'       => 'interactive',
                'age_min'             => 72,
                'age_max'             => 120,
                'duration_minutes'    => 10,
                'difficulty'          => 'medium',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'For gifted children who rarely fail: deliberately introduce age-appropriate challenges they WILL fail at, to give them practice with the failure-and-learn cycle while the stakes are manageable'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'metacognition'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '📈',
            ],
            [
                'title'               => 'STOP-THINK-ACT — Impulse Control Framework (Ages 6–9)',
                'description'         => 'A simple three-step self-regulation framework taught explicitly and practiced during calm moments so it activates automatically in heated moments. Bridges emotional regulation and executive functioning.',
                'instructions'        => "Introduce during a calm teaching moment:\n1. STOP: When you feel a BIG feeling, freeze your body like a statue.\n2. THINK: Ask yourself three questions:\n   - 'What am I feeling?'\n   - 'What do I WANT to do right now?'\n   - 'Will that choice help or hurt?'\n3. ACT: Choose an action that helps.\n\nPractice with scenarios: 'Imagine someone took your pencil. STOP. THINK. ACT. What did you decide?'\nRole-play 5–10 different scenarios until automatic.",
                'instructions_for_parent' => 'Post the STOP-THINK-ACT steps visually in the child\'s room. During a real incident, simply say quietly: "STOP." Wait. Then: "What do you think?" This is NOT the time for lecturing — it\'s a prompt for them to run the process.',
                'activity_type'       => 'interactive',
                'age_min'             => 72,
                'age_max'             => 108,
                'duration_minutes'    => 15,
                'difficulty'          => 'medium',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with just STOP and one question: "Will this help or hurt?"', 'harder' => 'Add a 4th step: REVIEW — after the situation, evaluate how your choice worked'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'metacognition'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🚦',
            ],
            [
                'title'               => 'Conflict Resolution Peace Table (Ages 6–10)',
                'description'         => 'A structured conflict resolution process taught during calm times for use during conflicts — between siblings, with friends, or with parents. Based on peer mediation principles from social-emotional learning curricula.',
                'instructions'        => "Set up: A designated table or neutral space is the Peace Table. Only peaceful words allowed there.\n\nProtocol (with a parent as mediator initially):\n1. Each person states: 'I feel ___ when ___ because ___.' (No interrupting.)\n2. Each person states what they WANT.\n3. Together: 'What can we both agree to try?'\n4. Shake hands or high-five as a peace seal.\n5. Parent gradually steps back as children internalise the steps.",
                'instructions_for_parent' => 'The Peace Table takes months to establish but becomes self-managing. Eventually children will say to each other: "Let\'s go to the Peace Table." This is one of the most profound gifts you can give siblings.',
                'activity_type'       => 'interactive',
                'age_min'             => 72,
                'age_max'             => 120,
                'duration_minutes'    => 20,
                'difficulty'          => 'medium',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'Introduce a "talking object" (a smooth stone, a small toy) — only the person holding the object can speak. This prevents interruptions and teaches deep listening.'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'executive_function', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'emoji'               => '🕊️',
            ],
            [
                'title'               => 'Daily Bedtime Emotion Review — Heart Journal',
                'description'         => 'A 5-minute nightly ritual that combines gratitude, emotional processing, and connection. The child reflects on their three emotional peaks of the day — highest, lowest, and most unexpected. Builds emotional vocabulary, metacognition, and parent-child connection simultaneously.',
                'instructions'        => "Each night before sleep:\n1. Ask: 'What was the best feeling you had today? When was it?'\n2. Ask: 'Was there a time today when feelings felt hard? What happened?'\n3. Ask: 'Was there something that surprised you — in your feelings or someone else\'s?'\n4. Parent shares one of their own (genuinely — not performed).\n5. Close: 'Is there anything your heart needs to say before sleep?'\n6. End with a du\'a or blessing together.",
                'instructions_for_parent' => 'The regularity is what makes this powerful, not the length. Even 3 minutes of consistent emotional connection every night builds a child who talks to you about their feelings — which is the greatest gift you can give them as they age into adolescence.',
                'activity_type'       => 'mindfulness',
                'age_min'             => 60,
                'age_max'             => 120,
                'duration_minutes'    => 5,
                'difficulty'          => 'easy',
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['variation' => 'For children who don\'t readily open up: start with the parent sharing first — children copy what they see'],
                'cognitive_domain'    => 'emotional_regulation',
                'developmental_domains' => ['social_emotional', 'metacognition', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'emoji'               => '🌙',
            ],
        ]);
    }
}
