<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;

/**
 * Executive Functioning Seeder
 *
 * Covers the three core EF domains (working memory, inhibitory control,
 * cognitive flexibility) plus East Asian cognitive training techniques:
 * - Soroban / Mental Abacus (Japanese mental arithmetic)
 * - Shichida Method flash training (right-brain speed processing)
 * - Kumon-style mastery scaffolding (procedural automaticity)
 * - Chinese stroke-order / calligraphy focus drills
 * - Go / Five-in-a-row strategic pattern games
 */
class ExecutiveFunctionSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('🧠 Seeding Executive Functioning activities...');

        foreach ($this->activities() as $data) {
            Activity::create($data);
        }

        $this->command->info('✅ Executive Functioning activities seeded: ' . count($this->activities()));
    }

    private function activities(): array
    {
        $base = [
            'language'   => 'en',
            'is_free'    => false,
            'difficulty' => 'medium',
        ];

        return array_map(fn($a) => array_merge($base, $a), [

            // ═══════════════════════════════════════════════════════════════
            // BABIES (0–12 months) — Foundational EF: Object Permanence,
            // Proto-Inhibitory Control, Simple Attention Focus
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Peek-a-Boo Object Permanence',
                'description'         => 'Parent hides a favourite toy under a cloth and asks "Where did it go?" Baby searches for and finds the hidden object, building the understanding that things still exist even when out of sight.',
                'instructions'        => "1. Show baby an interesting toy.\n2. Slowly cover it with a soft cloth.\n3. Ask excitedly: 'Where did it go?'\n4. Wait 3–5 seconds for baby to reach for it.\n5. Lift cloth together and celebrate: 'You found it!'\n6. Repeat 3–4 times.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 6,
                'age_max'             => 12,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => ['Ensure cloth is lightweight and can never cover face or block airways', 'Use only baby-safe toys with no small parts'],
                'adaptations'         => ['easier' => 'Hide the toy with only half covered so baby can still see part of it', 'harder' => 'Hide the toy behind a box so it is completely invisible, or move it to a second location'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['cognitive', 'social_emotional', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'difficulty'          => 'easy',
                'emoji'               => '🙈',
            ],
            [
                'title'               => 'Wait for the Rattle',
                'description'         => 'A proto-inhibitory control game where baby sees the rattle being shaken, is encouraged to wait while parent pauses, then hears it again. Builds the earliest form of anticipatory delay.',
                'instructions'        => "1. Hold rattle in front of baby.\n2. Shake it — baby reaches and looks.\n3. Hold still and pause for 3 seconds (say 'Wait, wait...').\n4. Shake again.\n5. Gradually extend the pause by 1 second each turn.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 4,
                'age_max'             => 10,
                'duration_minutes'    => 5,
                'mess_level'          => 'low',
                'safety_warnings'     => ['Ensure rattle has no small parts or sharp edges', 'Supervise closely'],
                'adaptations'         => ['easier' => 'Shorten the pause to 1 second', 'harder' => 'Add a second rattle and switch between them to vary the sound'],
                'cognitive_domain'    => 'inhibitory_control',
                'developmental_domains' => ['cognitive', 'sensory', 'social_emotional'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'difficulty'          => 'easy',
                'emoji'               => '🎵',
            ],
            [
                'title'               => 'Two-Toy Choice Game',
                'description'         => 'Presenting baby with two clearly different objects and teaching them to reach and choose — the earliest form of decision-making that activates the prefrontal cortex.',
                'instructions'        => "1. Hold two clearly different objects (e.g., a soft ball and a ring).\n2. Hold them equally at baby\'s eye level.\n3. Watch where baby looks first, then reaches.\n4. Name the choice: \'You chose the ball!\'\n5. Play with baby using their chosen object for 2 minutes.\n6. Offer the choice again.",
                'subject'             => 'executive_function',
                'activity_type'       => 'play',
                'age_min'             => 5,
                'age_max'             => 12,
                'duration_minutes'    => 8,
                'mess_level'          => 'low',
                'safety_warnings'     => ['All objects must be large enough that they cannot be swallowed — minimum 4cm diameter', 'Supervise at all times'],
                'adaptations'         => ['easier' => 'Use objects with very contrasting colours and sizes', 'harder' => 'Use three objects and pause after each choice to observe preference patterns'],
                'cognitive_domain'    => 'inhibitory_control',
                'developmental_domains' => ['cognitive', 'fine_motor', 'social_emotional'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'difficulty'          => 'easy',
                'emoji'               => '🎯',
            ],

            // ═══════════════════════════════════════════════════════════════
            // TODDLERS (12–36 months) — EF Foundations: Stop/Go, Simple Rules,
            // Switching, 2-Step Directions
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Stop & Go Music Game',
                'description'         => 'A classic inhibitory control builder — children dance freely when music plays, and freeze like statues the instant it stops. This simple game trains the "brake" system in the brain.',
                'instructions'        => "1. Play upbeat music and dance together.\n2. Stop the music suddenly.\n3. Say 'Freeze!' and stop all movement.\n4. Hold the freeze for 3-5 seconds.\n5. Restart music and dance again.\n6. Play 8–10 rounds, gradually lengthening freeze time.",
                'subject'             => 'executive_function',
                'activity_type'       => 'movement',
                'age_min'             => 18,
                'age_max'             => 36,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => ['Clear the play area of obstacles before starting', 'Ensure flooring is non-slip'],
                'adaptations'         => ['easier' => 'Use a visual cue (raise your hand) in addition to stopping the music', 'harder' => 'Add a rule: freeze in a specific pose (like a dinosaur or a tree)'],
                'cognitive_domain'    => 'inhibitory_control',
                'developmental_domains' => ['gross_motor', 'executive_function', 'social_emotional'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'easy',
                'emoji'               => '⏸️',
            ],
            [
                'title'               => 'Simon Says for Toddlers',
                'description'         => 'A simplified Simon Says that teaches toddlers to listen carefully and only act when they hear the magic words — building inhibitory control in a joyful, social way.',
                'instructions'        => "1. Explain: 'Only move when I say Simon Says first!'\n2. Say 'Simon says touch your toes' — everyone does it.\n3. Say 'Touch your nose' (without Simon says) — stay still.\n4. Start slowly with only 3-4 commands.\n5. Celebrate every correct response.\n6. Increase pace gradually.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 24,
                'age_max'             => 42,
                'duration_minutes'    => 12,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Always start with "Simon says" — do not use trick commands until the child has mastered the concept', 'harder' => 'Increase speed and add movement commands like jump, spin, and clap'],
                'cognitive_domain'    => 'inhibitory_control',
                'developmental_domains' => ['gross_motor', 'executive_function', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'easy',
                'emoji'               => '🤸',
            ],
            [
                'title'               => 'Sort by Color, Then Switch to Shape',
                'description'         => 'A cognitive flexibility exercise — children sort objects by one rule (color), then when the rule changes to shape, they must override their previous approach. This is the brain\'s "gear-shifting" ability.',
                'instructions'        => "1. Put out 8–12 objects that vary in both colour and shape.\n2. Round 1: 'Put all the RED things together.'\n3. Child sorts by colour. Celebrate success.\n4. Round 2: 'Now let\'s play a different game. Put all the CIRCLES together.'\n5. If child keeps sorting by colour, gently redirect.\n6. End with: 'Amazing! You switched your thinking!'",
                'subject'             => 'executive_function',
                'activity_type'       => 'sorting',
                'age_min'             => 24,
                'age_max'             => 48,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => ['Ensure sorting objects are too large to swallow if toddlers are under 3'],
                'adaptations'         => ['easier' => 'Only switch once (from colour to shape) and use very familiar colours and shapes', 'harder' => 'Add a third sorting rule (e.g., by size) and switch unpredictably'],
                'cognitive_domain'    => 'cognitive_flexibility',
                'developmental_domains' => ['cognitive', 'executive_function', 'fine_motor'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🔄',
            ],
            [
                'title'               => 'Two-Step Instruction Challenge',
                'description'         => 'Following two-part instructions builds working memory. This activity makes it fun — child hears both instructions at once, holds them in mind, and executes them in order.',
                'instructions'        => "1. Explain: 'I'm going to give you TWO jobs to do. Listen to both first, then do them!'\n2. Give two-step instruction: 'First get your teddy, THEN give it a hug.'\n3. Wait and watch — do not repeat the instruction.\n4. Celebrate success. If forgotten: model and try again.\n5. Progress to more complex pairs: 'Clap twice, then jump once.'",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 24,
                'age_max'             => 42,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with one-step instructions until mastered, then add a second step gradually', 'harder' => 'Add three-step instructions or add a spatial component (go to bedroom, get teddy, bring it here)'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['executive_function', 'language', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '📋',
            ],

            // ═══════════════════════════════════════════════════════════════
            // PRESCHOOL (36–72 months) — EF Development + East Asian Cognitive
            // Techniques: Flash Cards, Soroban Intro, Mandala Memory
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Red Light, Green Light',
                'description'         => 'The classic outdoor game that trains inhibitory control and sustained attention. Children must resist the urge to keep running on "Red Light" and respond instantly to "Green Light."',
                'instructions'        => "1. One player is the 'traffic light' at one end of the space.\n2. Others start at the opposite end.\n3. Traffic light calls 'Green Light!' — everyone runs toward them.\n4. Traffic light calls 'Red Light!' and turns around — everyone must freeze.\n5. Anyone caught moving goes back to the start.\n6. First to reach the traffic light wins and becomes the next traffic light.",
                'subject'             => 'executive_function',
                'activity_type'       => 'movement',
                'age_min'             => 36,
                'age_max'             => 72,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => ['Play in an open, obstacle-free space', 'Ensure all children understand the rules before starting'],
                'adaptations'         => ['easier' => 'Add a visual cue — hold up green/red paper circles as well as saying the words', 'harder' => 'Add "Yellow Light" (walk slowly) for three-way control'],
                'cognitive_domain'    => 'inhibitory_control',
                'developmental_domains' => ['gross_motor', 'executive_function', 'social_emotional'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'easy',
                'emoji'               => '🚦',
            ],
            [
                'title'               => 'Memory Card Game (Pairs)',
                'description'         => 'The memory matching game directly exercises working memory, visual pattern recognition, and inhibitory control (waiting for your turn). Start with 4 pairs (8 cards) and progress to 12+ pairs.',
                'instructions'        => "1. Lay cards face down in a grid.\n2. Player 1 flips two cards. If they match, keep the pair.\n3. If no match, flip back — remember where they are!\n4. Player 2 takes a turn.\n5. Count pairs at the end — most pairs wins.\n6. Track progress: can child remember more pairs over time?",
                'subject'             => 'executive_function',
                'activity_type'       => 'matching',
                'age_min'             => 42,
                'age_max'             => 72,
                'duration_minutes'    => 20,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with only 3 pairs (6 cards) using very distinct images', 'harder' => 'Use 10+ pairs, or add a timer to create productive pressure'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['cognitive', 'executive_function', 'social_emotional'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🃏',
            ],
            [
                'title'               => 'Opposite Day Game',
                'description'         => 'When it is "Opposite Day," everything is reversed — child must do the opposite of what is said. A powerful cognitive flexibility exercise that overrides automatic responses.',
                'instructions'        => "1. Declare: 'Today is OPPOSITE DAY! When I say stand UP, you sit DOWN.'\n2. Practice together: 'Stand up!' — child must sit.\n3. Keep going: 'Hands on head!' — child puts hands on floor.\n4. 'Clap your hands!' — child stomps feet.\n5. Start slowly. Speed up as child improves.\n6. Let child take a turn being the caller.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 42,
                'age_max'             => 72,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Only play for 2–3 pairs of opposites at a time with clear signals', 'harder' => 'Include language opposites: hot/cold, fast/slow, and switch mid-game without warning'],
                'cognitive_domain'    => 'cognitive_flexibility',
                'developmental_domains' => ['executive_function', 'language', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '↕️',
            ],

            // ─── Shichida Flash Dot Training ────────────────────────────
            [
                'title'               => 'Flash Dot Counting — Shichida Subitizing (Ages 4+)',
                'description'         => 'Inspired by the Shichida Method right-brain training. Flash a card showing a random arrangement of dots for exactly 1 second. Child calls out the quantity without counting. This trains subitizing — the ability to instantly perceive quantity — and activates rapid visual processing centers in the right brain.',
                'instructions'        => "1. Prepare cards with dot arrays: 1–5 dots arranged randomly (not in patterns).\n2. Hold a card so child cannot see it.\n3. Flash it for exactly 1 second (cover quickly).\n4. Ask: 'How many dots did you see?'\n5. Do NOT allow time to count. Praise instant answers.\n6. Progress: start with 1–3 dots, graduate to 1–7 over weeks.\n7. Suggested pace: 2–3 cards per minute, 5-minute sessions.",
                'subject'             => 'executive_function',
                'activity_type'       => 'flashcard',
                'age_min'             => 48,
                'age_max'             => 84,
                'duration_minutes'    => 5,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use 1–3 dots only; arrange them in familiar patterns like dice faces', 'harder' => 'Increase to 8–10 dots in irregular arrangements; reduce flash time to half a second'],
                'cognitive_domain'    => 'subitizing',
                'developmental_domains' => ['numeracy', 'cognitive', 'executive_function'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'collaborative',
                'difficulty'          => 'medium',
                'emoji'               => '⚫',
            ],
            [
                'title'               => 'Mandala Observation Memory — Shichida (Ages 4+)',
                'description'         => 'Based on the Shichida photographic memory technique. Child studies a coloured mandala pattern for 10 seconds, then recreates it from memory by colouring a blank version. Trains visual working memory, spatial reasoning, and sustained attention.',
                'instructions'        => "1. Show child a simple, coloured mandala pattern.\n2. Say: 'Look at this carefully. You have 10 seconds to remember every colour.'\n3. Child studies silently (no talking).\n4. After 10 seconds, cover or remove the original.\n5. Child colours a blank mandala template from memory.\n6. Reveal original and compare — celebrate accuracy!\n7. Keep the blank template simple: 4–8 sections initially.",
                'subject'             => 'executive_function',
                'activity_type'       => 'drawing',
                'age_min'             => 48,
                'age_max'             => 84,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use only 2 colours and 4 sections; allow 20 seconds of observation time', 'harder' => 'Use 6+ colours and 12 sections; reduce observation time to 5 seconds'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['cognitive', 'creative_arts', 'executive_function', 'fine_motor'],
                'materials_cost'      => 'low',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🌸',
            ],
            [
                'title'               => 'Image Linking Story Chain — Shichida (Ages 4+)',
                'description'         => 'The Shichida linking memory technique. Show 5 pictures one by one, each for 2 seconds. Child creates a silly story connecting them in order, then recalls all 5. Trains sequential working memory and creative narrative thinking.',
                'instructions'        => "1. Prepare 5 simple picture cards (e.g., lion, umbrella, apple, star, shoe).\n2. Show each picture for 2 seconds.\n3. As you show each one, help child weave a silly story: 'A lion was walking with an umbrella...'\n4. After all 5: hide the cards.\n5. Ask child to recall the story and list all 5 items.\n6. Progress to 7–10 items over several weeks.",
                'subject'             => 'executive_function',
                'activity_type'       => 'story',
                'age_min'             => 48,
                'age_max'             => 84,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with only 3 pictures and allow 5 seconds per image', 'harder' => 'Use 8–10 pictures, reduce viewing time to 1 second each, don\'t narrate — let child build the story alone'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['cognitive', 'language', 'executive_function'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🔗',
            ],

            // ─── Soroban Introduction ───────────────────────────────────
            [
                'title'               => 'Soroban Abacus Introduction — Counting 1 to 9 (Ages 4–5)',
                'description'         => 'Stage 1 of the Japanese Soroban (そろばん) mental arithmetic program. Children learn to represent numbers 1–9 on a physical abacus by moving beads. This builds tactile number sense and a mental visual model that will be used for mental arithmetic in later stages.',
                'instructions'        => "1. Use a standard Soroban or any 1-column abacus with 5 beads.\n2. Place 1 earth bead (bottom): 'This is 1.'\n3. Place 2 earth beads: 'This is 2.' Continue to 4.\n4. Explain the heaven bead (top, worth 5): push it down = 5.\n5. Practice: 5+1 = push heaven bead down, add 1 earth bead = 6.\n6. Practice representing numbers 1–9 daily for 5 minutes.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 48,
                'age_max'             => 72,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Only practice 1–4 (earth beads only) in week 1; introduce the heaven bead only when solid', 'harder' => 'Practice simple addition: enter 3, then add 2, what does the abacus show?'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['numeracy', 'fine_motor', 'cognitive', 'executive_function'],
                'materials_cost'      => 'low',
                'parent_involvement'  => 'collaborative',
                'difficulty'          => 'medium',
                'emoji'               => '🧮',
            ],
            [
                'title'               => 'Finger Soroban — Imaginary Bead Movements (Ages 5–7)',
                'description'         => 'Stage 2 of the Soroban sequence. Having learned physical bead movements, children now mime the same movements without an abacus — fingers moving as if beads are there. This builds the internal mental model of the abacus that enables mental arithmetic.',
                'instructions'        => "1. Child places hands as if holding an invisible Soroban.\n2. Say a number: '3' — child moves fingers to represent 3 earth beads.\n3. Progress to: 'Add 2' — child adjusts fingers mentally.\n4. Verify by having child state the result.\n5. Begin with single digits only (1+2, 3+1, 4+2).\n6. Aim for fluid, automatic finger movements.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 60,
                'age_max'             => 84,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Keep the physical abacus nearby for reference until movements are automatic', 'harder' => 'Add two 1-digit numbers mentally, progress to two 2-digit numbers over months'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['numeracy', 'executive_function', 'spatial_reasoning'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'hard',
                'emoji'               => '✋',
            ],

            // ─── Chinese Calligraphy Focus Drills ───────────────────────
            [
                'title'               => 'Pre-Writing Stroke Practice — Chinese-Style (Ages 4–5)',
                'description'         => 'Drawing the foundational strokes of Chinese brush calligraphy (书法 shūfǎ) — horizontal (横), vertical (竖), and diagonal (撇/捺) lines. This meditative, precision activity trains fine motor control, spatial awareness, sustained focus, and a calm mind-state that transfers to all learning activities.',
                'instructions'        => "1. Use a large piece of paper and a broad-tip marker or natural brush with ink.\n2. Demonstrate a slow, controlled horizontal stroke: left to right, even pressure.\n3. Child traces, then draws their own.\n4. Move to vertical strokes (top to bottom).\n5. Add diagonal strokes.\n6. Emphasise: 'Slow and controlled is better than fast.'\n7. Practise 3 strokes for 5 minutes each session.\n8. Aim for meditative, focused silence during practice.",
                'subject'             => 'executive_function',
                'activity_type'       => 'drawing',
                'age_min'             => 48,
                'age_max'             => 72,
                'duration_minutes'    => 10,
                'mess_level'          => 'medium',
                'safety_warnings'     => ['Ensure ink is non-toxic and washable', 'Cover work surface — ink can stain'],
                'adaptations'         => ['easier' => 'Use pencil on dotted guide lines — child traces before drawing freehand', 'harder' => 'Add curved strokes (弯 wān) and hooks; combine strokes to make a simple character like 一 (one) or 十 (ten)'],
                'cognitive_domain'    => 'attention',
                'developmental_domains' => ['fine_motor', 'executive_function', 'spatial_reasoning'],
                'materials_cost'      => 'low',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🖌️',
            ],
            [
                'title'               => 'Chinese Number Characters — 一二三 (Ages 5–7)',
                'description'         => 'Learning to write the Chinese characters for numbers 1–3 (一yī, 二èr, 三sān). These simple characters are made from the horizontal stroke already practiced and are ideal for introducing sequential stroke order — a core concept in Chinese writing systems.',
                'instructions'        => "1. Show flashcard: 一 (one) — one horizontal stroke.\n2. Demonstrate stroke direction with arrow.\n3. Child traces character 5 times.\n4. Child writes from memory 5 times.\n5. Repeat for 二 (two) and 三 (three).\n6. Compare child\'s characters to the model — celebrate precision.\n7. Teach the meaning: this is how over 1.4 billion people write 'one'.",
                'subject'             => 'executive_function',
                'activity_type'       => 'drawing',
                'age_min'             => 60,
                'age_max'             => 84,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with 一 only (single stroke). Add 二 in week 2 and 三 in week 3', 'harder' => 'Progress to 大 (dà — big) and 小 (xiǎo — small) using similar strokes'],
                'cognitive_domain'    => 'sequential_thinking',
                'developmental_domains' => ['fine_motor', 'executive_function', 'language', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🀄',
            ],

            // ═══════════════════════════════════════════════════════════════
            // SCHOOL (72–120 months) — Advanced EF: Mental Math, Strategic
            // Thinking, Self-Regulation, Metacognition, Go/Chess Strategy
            // ═══════════════════════════════════════════════════════════════

            [
                'title'               => 'Mental Soroban — Visualise and Calculate (Ages 6–8)',
                'description'         => 'Stage 3 of the Soroban sequence: purely mental arithmetic without any physical tool or finger movements. Children have internalised the abacus image and now compute by moving imaginary beads entirely in their mind — a powerful working memory and spatial reasoning exercise.',
                'instructions'        => "1. Ensure child has mastered Finger Soroban first.\n2. Sit comfortably, eyes can be closed or looking down.\n3. Say: 'Imagine your Soroban in your mind.'\n4. Give addition problem: '4 + 3 = ?'\n5. Child solves by mentally moving beads.\n6. Progress: 2-digit additions (23 + 14).\n7. Aim for 20 problems in 5 minutes over 3 months.",
                'subject'             => 'executive_function',
                'activity_type'       => 'quiz',
                'age_min'             => 72,
                'age_max'             => 96,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Return to Finger Soroban if child struggles — do not rush to purely mental until movements are automatic', 'harder' => 'Progress to subtraction, then 3-digit numbers, then timed challenges'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['numeracy', 'executive_function', 'spatial_reasoning'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'independent',
                'difficulty'          => 'hard',
                'emoji'               => '💡',
            ],
            [
                'title'               => 'Kumon-Style Daily Math Drill (Ages 6–9)',
                'description'         => 'Inspired by the Kumon (公文式) method — a 10-minute daily drill of age-appropriate maths problems, slightly below the child\'s challenge level for fluency building. The goal is automaticity and confidence. Mastery is tracked: child advances only when accuracy exceeds 80% for 3 consecutive days.',
                'instructions'        => "1. Prepare a single-page sheet of 20 problems at child's current level.\n2. Set timer for 10 minutes.\n3. Child works independently and silently.\n4. Mark together when done.\n5. Record score and time.\n6. If score ≥ 80% for 3 days: advance to next level.\n7. If score < 60%: return to one level below.\n8. Celebrate small wins — the streak matters more than perfection.",
                'subject'             => 'executive_function',
                'activity_type'       => 'quiz',
                'age_min'             => 72,
                'age_max'             => 108,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Reduce to 10 problems; allow reference to number line or counting aids', 'harder' => 'Increase to 30 problems; add a speed bonus for finishing before time ends'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['numeracy', 'executive_function', 'metacognition'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'independent',
                'difficulty'          => 'hard',
                'emoji'               => '📝',
            ],
            [
                'title'               => 'Five-in-a-Row Strategic Grid Game (Ages 6–10)',
                'description'         => 'Adapted from the Chinese game 五子棋 (Wǔzǐqí — Five-in-a-Row). Players take turns placing pieces on a grid, aiming to form a line of 5. Trains forward planning, pattern recognition, inhibitory control (thinking before placing), and strategic flexibility.',
                'instructions'        => "1. Draw a 10x10 grid on paper (or use a game board).\n2. Each player gets a colour (X or O, or coloured stones).\n3. Take turns placing one piece per turn.\n4. First to get 5 in a row (horizontal, vertical, or diagonal) wins.\n5. Before each move, ask: 'What is your plan? What will your opponent do?'\n6. Review the game after: 'What was the turning point?'",
                'subject'             => 'executive_function',
                'activity_type'       => 'matching',
                'age_min'             => 72,
                'age_max'             => 120,
                'duration_minutes'    => 25,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Play on a 5x5 grid with 3-in-a-row rule (Tic-Tac-Toe extension)', 'harder' => 'Add a rule: cannot win in the exact centre of the board, or play on a 15x15 Gomoku board'],
                'cognitive_domain'    => 'sequential_thinking',
                'developmental_domains' => ['cognitive', 'executive_function', 'social_emotional'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'hard',
                'emoji'               => '⚫',
            ],
            [
                'title'               => 'Peg Memory System — Number-Image Association (Ages 6–9)',
                'description'         => 'The Shichida Peg Memory technique: child links each number 1–10 to a vivid image (1=pencil, 2=swan, 3=ear, etc.). Then uses these pegs to memorise random lists by creating mental scenes. Trains both the number system and associative working memory.',
                'instructions'        => "1. Teach child the peg list (one per week): 1=pencil, 2=swan, 3=ear, 4=sail, 5=hook, 6=cherry, 7=cliff, 8=glasses, 9=balloon, 10=bat-and-ball.\n2. Drill pegs daily: 'What is number 5?' → 'Hook!'\n3. Once pegs are solid, give 5 random words to remember.\n4. Child links each word dramatically to its peg number.\n5. Recall: 'What was word number 3?' — child visualises peg scene.\n6. Aim for 10-item recall within a month.",
                'subject'             => 'executive_function',
                'activity_type'       => 'matching',
                'age_min'             => 72,
                'age_max'             => 108,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with pegs 1–5 only; use very vivid images suggested by the child', 'harder' => 'Extend to 20 pegs; use it to memorise Quran verses, multiplication table, or science facts'],
                'cognitive_domain'    => 'working_memory',
                'developmental_domains' => ['cognitive', 'executive_function', 'numeracy'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'hard',
                'emoji'               => '🎯',
            ],
            [
                'title'               => 'Emotion Thermometer Journaling (Ages 6–9)',
                'description'         => 'A metacognitive exercise combining emotional regulation with executive functioning. Child draws a "thermometer" and marks where their feelings are at the start and end of each day, then writes or draws why. Builds emotional self-awareness and metacognition.',
                'instructions'        => "1. Draw a thermometer with levels 1–10.\n2. Label levels: 1=calm, 4=a bit worried, 7=frustrated, 10=overwhelmed.\n3. Morning check-in: 'Where is your thermometer today? Why?'\n4. Child marks the level and writes/draws the reason.\n5. End of day: repeat.\n6. Over a week, look for patterns: 'When does your thermometer go high?'\n7. Brainstorm cool-down strategies together.",
                'subject'             => 'executive_function',
                'activity_type'       => 'drawing',
                'age_min'             => 72,
                'age_max'             => 108,
                'duration_minutes'    => 10,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use only 5 levels and use emojis instead of numbers', 'harder' => 'Add a "regulation plan" section: write what strategy you will use when temperature is above 7'],
                'cognitive_domain'    => 'metacognition',
                'developmental_domains' => ['emotional_regulation', 'executive_function', 'language'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'medium',
                'emoji'               => '🌡️',
            ],
            [
                'title'               => 'Brain Breaks — 2-Minute Mindful Reset',
                'description'         => 'A structured 2-minute pause between intense cognitive activities. Combines box breathing (4-4-4-4) with a gentle body scan. Research shows short mindfulness breaks improve subsequent attention and working memory performance by up to 30%.',
                'instructions'        => "1. Stop all activity. Child finds a comfortable position (seated or lying).\n2. Box Breathing x3: breathe IN for 4 counts, HOLD for 4, OUT for 4, HOLD for 4.\n3. Body Scan: 'Feel your feet on the floor... your hands resting... your face relaxed...'\n4. 30 seconds of silence.\n5. Open eyes. Ask: 'How do you feel now compared to before?'\n6. Return to learning with renewed focus.",
                'subject'             => 'executive_function',
                'activity_type'       => 'mindfulness',
                'age_min'             => 60,
                'age_max'             => 120,
                'duration_minutes'    => 3,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Use 3-count breathing (in for 3, out for 3) for younger or anxious children', 'harder' => 'Add a visualisation: imagine a favourite peaceful place in detail'],
                'cognitive_domain'    => 'attention',
                'developmental_domains' => ['executive_function', 'emotional_regulation', 'metacognition'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'guided',
                'difficulty'          => 'easy',
                'emoji'               => '🧘',
            ],
            [
                'title'               => 'Sustained Attention Challenge — 15-Minute Focus Task (Ages 6–8)',
                'description'         => 'A structured daily exercise in maintaining attention for 15 continuous minutes on a single, mildly engaging task. Builds the focus stamina essential for academic success and maps directly to the EF milestone of sustained attention.',
                'instructions'        => "1. Choose a quiet task: puzzle, coloring with detail, pattern copying, or model building.\n2. Set a visible timer for 15 minutes.\n3. Rule: one task only. No breaks. No switching.\n4. If distracted, gently self-redirect: 'Can you bring your attention back?'\n5. At end: celebrate the full focus time.\n6. Track streak over days/weeks on a chart.\n7. Goal: 15 minutes consistently before extending.",
                'subject'             => 'executive_function',
                'activity_type'       => 'interactive',
                'age_min'             => 72,
                'age_max'             => 96,
                'duration_minutes'    => 15,
                'mess_level'          => 'low',
                'safety_warnings'     => [],
                'adaptations'         => ['easier' => 'Start with 5 minutes; increase by 2 minutes per week', 'harder' => 'Introduce a mild distraction (quiet background noise) to challenge attention stability'],
                'cognitive_domain'    => 'attention',
                'developmental_domains' => ['executive_function', 'metacognition', 'cognitive'],
                'materials_cost'      => 'free',
                'parent_involvement'  => 'independent',
                'difficulty'          => 'medium',
                'emoji'               => '⏱️',
            ],
        ]);
    }
}
