[program:noblenest-horizon]
process_name=%(program_name)s
command=php8.3 /var/www/noblenest/artisan horizon
autostart=true
autorestart=true
user=deploy
redirect_stderr=true
stdout_logfile=/var/www/noblenest/storage/logs/horizon.log
stopwaitsecs=3600
