<?php

namespace App\Services\Providers\Whisper;

use App\Services\Providers\WhisperAdapter;

/**
 * Phase 6 — local/stub Whisper adapter for tests and dev.
 *
 * Returns a fixed, valid WebVTT document. Never makes network calls.
 */
class LocalWhisperAdapter implements WhisperAdapter
{
    public function transcribeToVtt(string $mediaUrl, string $locale): string
    {
        return <<<VTT
WEBVTT

00:00:00.000 --> 00:00:03.000
[stub transcript for {$locale}]

00:00:03.000 --> 00:00:06.000
Generated by LocalWhisperAdapter.
VTT;
    }
}
